namespace TestsCommon;

public static class CSharpKnownIssues
{
    /// <summary>
    /// Gets known issues
    /// </summary>
    /// <param name="versionEnum">version to get the known issues for</param>
    /// <returns>A mapping of test names into known CSharp issues</returns>
    public static Dictionary<string, KnownIssue> GetCSharpCompilationKnownIssues(Versions versionEnum)
    {
        var version = versionEnum.ToString();
        return new Dictionary<string, KnownIssue>()
            {
                {$"delete-userflowlanguagepage-csharp-{version}-compiles", new KnownIssue(Category.SDK, StreamRequestDoesNotSupportDelete) },
                {$"unfollow-site-csharp-{version}-compiles", new KnownIssue(Category.SDK, "SDK doesn't convert actions defined on collections to methods.", "https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/250") },
                {$"follow-site-csharp-{version}-compiles", new KnownIssue(Category.SDK, "SDK doesn't convert actions defined on collections to methods.", "https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/250") },
                { "get-android-count-csharp-V1-compiles", CountIsNotSupportedKnownIssue },
                {$"get-group-transitivemembers-count-csharp-{version}-compiles", CountIsNotSupportedKnownIssue },
                { "get-transitivereports-csharp-Beta-compiles", CountIsNotSupportedKnownIssue},
                {$"get-phone-count-csharp-{version}-compiles", SearchHeaderIsNotSupportedKnownIssue },
                {$"get-team-count-csharp-{version}-compiles", SearchHeaderIsNotSupportedKnownIssue },
                {$"get-tier-count-csharp-{version}-compiles", SearchHeaderIsNotSupportedKnownIssue },
                {$"get-wa-count-csharp-{version}-compiles", SearchHeaderIsNotSupportedKnownIssue },
                {$"get-web-count-csharp-{version}-compiles", SearchHeaderIsNotSupportedKnownIssue },
                {$"get-rooms-in-roomlist-csharp-{version}-compiles", new KnownIssue(Category.SDK, "SDK doesn't generate type segment in OData URL.", GitHubIssue: "https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/239") },
                { "create-externaldomainname-from--csharp-Beta-compiles", TypeCastIsNotSupportedKnownIssue},
                { "list-externaldomainname-csharp-Beta-compiles", TypeCastIsNotSupportedKnownIssue},
                { "reportroot-getm365appplatformusercounts-csv-csharp-Beta-compiles", MissingContentPropertyKnownIssue },
                { "reportroot-getm365appplatformusercounts-json-csharp-Beta-compiles", MissingContentPropertyKnownIssue },
                { "reportroot-getm365appusercoundetail-csharp-Beta-compiles", MissingContentPropertyKnownIssue },
                { "reportroot-getm365appusercountdetail-csharp-Beta-compiles", MissingContentPropertyKnownIssue },
                { "reportroot-getm365appusercounts-csv-csharp-Beta-compiles", MissingContentPropertyKnownIssue },
                { "reportroot-getm365appusercounts-json-csharp-Beta-compiles", MissingContentPropertyKnownIssue },
                { "get-transitivereports-user-csharp-Beta-compiles", CountIsNotSupportedKnownIssue},
                { "caseexportoperation-getdownloadurl-csharp-Beta-compiles", TypeCastIsNotSupportedKnownIssue },
                { "remove-rejectedsender-from-group-csharp-V1-compiles", DeleteAsyncIsNotSupportedForReferencesKnownIssue },
                { "delete-acceptedsenders-from-group-csharp-V1-compiles", DeleteAsyncIsNotSupportedForReferencesKnownIssue },
                { $"send-sharing-invite-csharp-{version}-compiles", new KnownIssue(Category.SDK, "C# depends on nonguaranteed parameter ordering", "https://github.com/microsoftgraph/msgraph-sdk-dotnet/issues/1202")},
                { "put-b2xuserflows-apiconnectorconfiguration-postattributecollection-csharp-V1-compiles", new KnownIssue(Category.SDK, ComplexTypeNavigationProperties, ComplexTypeNavigationPropertiesGithubIssue) },
                { "put-b2xuserflows-apiconnectorconfiguration-postfederationsignup-csharp-V1-compiles", new KnownIssue(Category.SDK, ComplexTypeNavigationProperties, ComplexTypeNavigationPropertiesGithubIssue) },
                { "update-b2xuserflows-userflowidentityprovider-csharp-Beta-compiles", new KnownIssue(Category.SDK, "IB2xIdentityUserFlowUserFlowIdentityProvidersCollectionReferencesRequest' does not contain a definition for 'UpdateAsync'")},
                { "update-b2cuserflows-userflowidentityproviders-csharp-Beta-compiles", new KnownIssue(Category.SDK, "IB2cIdentityUserFlowUserFlowIdentityProvidersCollectionReferencesRequest' does not contain a definition for 'UpdateAsync'")},
                { "post-administrativeunits-members-csharp-Beta-compiles", new KnownIssue(Category.SDK, "SDK doesn't convert actions defined on collections to methods.", "https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/250")},

                { "create-basetask-from--csharp-Beta-compiles", new KnownIssue(Category.HTTP, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-docs/issues/15575")},
                { "create-tasklist-from--csharp-Beta-compiles", new KnownIssue(Category.HTTP, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-docs/issues/15577")},
                { "deploymentaudience-updateaudience-csharp-Beta-compiles", new KnownIssue(Category.HTTP, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-docs/issues/12811")},
                { "get-devicecompliancepolicysettingstatesummary-csharp-Beta-compiles", new KnownIssue(Category.HTTP, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-docs/issues/13596")},
                { "list-administrativeunit-csharp-V1-compiles", new KnownIssue(Category.HTTP, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-docs/issues/12770")},
                { "list-devicecompliancepolicysettingstatesummary-csharp-Beta-compiles", new KnownIssue(Category.HTTP, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-docs/issues/13597")},
                { "update-tenantcustomizedinformation-csharp-Beta-compiles", new KnownIssue(Category.HTTP, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-docs/issues/13556")},
                { "update-basetask-csharp-Beta-compiles", new KnownIssue(Category.HTTP, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-docs/issues/15576") },
                { "update-tasklist-csharp-Beta-compiles", new KnownIssue(Category.HTTP, GitHubIssue: "https://github.com/microsoftgraph/microsoft-graph-docs/issues/15578")},

                { "put-b2cuserflows-apiconnectorconfiguration-postfederationsignup-csharp-Beta-compiles", StructuralPropertiesAreNotHandledKnownIssue },
                { "put-b2xuserflows-apiconnectorconfiguration-postfederationsignup-csharp-Beta-compiles", StructuralPropertiesAreNotHandledKnownIssue },
                { "put-b2xuserflows-apiconnectorconfiguration-postattributecollection-csharp-Beta-compiles", StructuralPropertiesAreNotHandledKnownIssue },
                { "put-b2cuserflows-apiconnectorconfiguration-postattributecollection-csharp-Beta-compiles", StructuralPropertiesAreNotHandledKnownIssue },

                { "create-datasource-from--1-csharp-Beta-compiles", NamespaceOdataTypeAnnotationsWithoutHashSymbolKnownIssue},
                { "create-deployment-from--csharp-Beta-compiles", NamespaceOdataTypeAnnotationsWithoutHashSymbolKnownIssue},
                { "create-noncustodialdatasource-from-email-csharp-Beta-compiles", NamespaceOdataTypeAnnotationsWithoutHashSymbolKnownIssue},
                { "create-noncustodialdatasource-from-siteurl-csharp-Beta-compiles", NamespaceOdataTypeAnnotationsWithoutHashSymbolKnownIssue},
                { "create-externalgroupmember-from--1-csharp-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Generation of non-existent class", "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/821") },
                { "create-externalgroupmember-from--2-csharp-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Generation of non-existent class", "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/821") },
                { "create-externalgroupmember-from--3-csharp-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Generation of non-existent class", "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/821") },
                { "create-externalregistration-csharp-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Online meeting registration uses addAsync instead of createAsync", "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/857")},
                { "basetask-delta-csharp-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Ids interpreted as path segments instead of as inputs", "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/836")},
                { "basetasklist-delta-csharp-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Ids interpreted as path segments instead of as inputs", "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/836")},
                { "delete-basetask-csharp-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Ids interpreted as path segments instead of as inputs", "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/836")},
                { "delete-checklistitem-csharp-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Ids interpreted as path segments instead of as inputs", "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/836")},
                { "delete-linkedresource-v2-csharp-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Ids interpreted as path segments instead of as inputs", "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/836")},
                { "get-basetask-csharp-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Ids interpreted as path segments instead of as inputs", "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/836")},
                { "get-basetasklist-csharp-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Ids interpreted as path segments instead of as inputs", "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/836")},
                { "get-checklistitem-csharp-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Ids interpreted as path segments instead of as inputs", "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/836")},
                { "get-linkedresource-v2-csharp-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Ids interpreted as path segments instead of as inputs", "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/836")},
                { "list-basetask-csharp-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Ids interpreted as path segments instead of as inputs", "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/836")},
                { "list-checklistitem-csharp-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Ids interpreted as path segments instead of as inputs", "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/836")},
                { "list-linkedresource-v2-csharp-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Ids interpreted as path segments instead of as inputs", "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/836")},
                { $"create-schema-from-connection-async-csharp-{version}-compiles", new KnownIssue(Category.SnippetGeneration, SnippetGenerationCreateAsyncSupport, SnippetGenerationCreateAsyncSupportGithubIssue) },
                { "update-deployment-1-csharp-Beta-compiles", NamespaceOdataTypeAnnotationsWithoutHashSymbolKnownIssue},
                { "update-deployment-2-csharp-Beta-compiles", NamespaceOdataTypeAnnotationsWithoutHashSymbolKnownIssue},
                { "reports-getuserarchivedprintjobs-csharp-Beta-compiles", DateTimeOffsetHandlingInUrlsKnownIssue },
                { "reports-getprinterarchivedprintjobs-csharp-Beta-compiles", DateTimeOffsetHandlingInUrlsKnownIssue },
                { "reports-getgrouparchivedprintjobs-csharp-Beta-compiles", DateTimeOffsetHandlingInUrlsKnownIssue },
                { "post-channelmessage-2-csharp-Beta-compiles", IdentitySetAndIdentityShouldNestAdditionalDataKnownIssue },
                { "post-chatmessage-2-csharp-Beta-compiles", IdentitySetAndIdentityShouldNestAdditionalDataKnownIssue},
                { "post-channelmessage-3-csharp-Beta-compiles", IdentitySetAndIdentityShouldNestAdditionalDataKnownIssue},
                { "post-channelmessage-3-csharp-V1-compiles", IdentitySetAndIdentityShouldNestAdditionalDataKnownIssue},
                { "post-channelmessage-2-csharp-V1-compiles", IdentitySetAndIdentityShouldNestAdditionalDataKnownIssue},
                { "post-chatmessage-2-csharp-V1-compiles", IdentitySetAndIdentityShouldNestAdditionalDataKnownIssue},

                { "create-educationrubric-from-educationassignment-csharp-V1-compiles", EducationAssignmentRubricContainsTargetPreprocessorKnownIssue},
                { "create-directorysetting-from-settings-for-guests-csharp-Beta-compiles", new KnownIssue(Category.Metadata, "GroupSetting undefined in metadata")},
                { "delete-educationrubric-from-educationassignment-csharp-V1-compiles", EducationAssignmentRubricContainsTargetPreprocessorKnownIssue},
                { "add-educationcategory-to-educationassignment-csharp-V1-compiles", EducationAssignmentRubricContainsTargetPreprocessorKnownIssue},

                { $"event-accept-csharp-{version}-compiles", EventActionsShouldNotBeReorderedKnownIssue },
                { $"event-decline-csharp-{version}-compiles", EventActionsShouldNotBeReorderedKnownIssue },
                { $"event-tentativelyaccept-csharp-{version}-compiles", EventActionsShouldNotBeReorderedKnownIssue },
                { $"create-homerealmdiscoverypolicy-from-serviceprincipal-csharp-Beta-compiles", new KnownIssue(Category.HTTP, RefNeeded) },
                { $"create-certificatebasedauthconfiguration-from-certificatebasedauthconfiguration-csharp-{version}-compiles", new KnownIssue(Category.HTTP, RefNeeded, "https://github.com/microsoftgraph/microsoft-graph-docs/issues/14004") },
                { $"create-tokenlifetimepolicy-from-application-csharp-Beta-compiles", new KnownIssue(Category.HTTP, RefNeeded) },

                { "team-put-schedule-2-csharp-Beta-compiles", NeedsAnalysisKnownIssue},
                { "create-directoryobject-from-orgcontact-1-csharp-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-directoryobject-from-orgcontact-2-csharp-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-csharp-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-connectorgroup-from-connector-csharp-Beta-compiles", NeedsAnalysisKnownIssue },
                { "managementactiontenantdeploymentstatus-changedeploymentstatus-csharp-Beta-compiles", NeedsAnalysisKnownIssue },
                { "search-query-csharp-Beta-compiles", NeedsAnalysisKnownIssue }
            };
    }

    /// <summary>
    /// Gets execution known issues
    /// </summary>
    /// <param name="versionEnum">version to get the execution known issues for</param>
    /// <returns>A mapping of test names into known CSharp issues</returns>
    public static Dictionary<string, KnownIssue> GetCSharpExecutionKnownIssues(Versions versionEnum)
    {
        var version = versionEnum.ToString();
        return new Dictionary<string, KnownIssue>()
            {
                { "get-resource-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/776" } },
                { "list-printusagebyuser-1-csharp-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "list-printusagebyprinter-2-csharp-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "list-printusagebyprinter-1-csharp-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "list-printusagebyuser-2-csharp-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "get-organizationalbranding-locale-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/777" } },
                { "get-chartgridlines-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-assignments-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-cloudpcgalleryimage-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-teams-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-customsecurityattributedefinition-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-attributeset-single-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-customsecurityattributedefinition-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-attendancerecord-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-endpoints-4-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-insightssettingspeoplerequest-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-organizationalbranding-locale-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-endpoints-5-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-endpoints-6-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-attributeset-all-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-attributeset-top-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-allowedvalue-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-attendancereports-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-customsecurityattributedefinition-filter-attributeset-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-authenticationcontextclassreference-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-cloudpcgalleryimage-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-customsecurityattributedefinition-filter-name-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-allowedvalue-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-resource-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-chartgridlines-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-permission-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-attributeset-orderby-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-endpoints-3-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-basetasklist-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "accesspackageassignment-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "accesspackageassignmentrequest-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "accessreviewinstance-filterbycurrentuser-csharp-Beta-executes", SDKFunctionParameterKnownIssue },
                { "accessreviewinstancedecisionitem-filterbycurrentuser-csharp-Beta-executes", SDKFunctionParameterKnownIssue },
                { "accessreviewscheduledefinition-filterbycurrentuser-csharp-Beta-executes", SDKFunctionParameterKnownIssue },
                { "authenticationmethodsroot-usersregisteredbyfeature-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "authenticationmethodsroot-usersregisteredbymethod-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "bookingbusiness-getcalendarview-csharp-Beta-executes", MissingDataKnownIssue },
                { "cloudpcauditevent-getauditactivitytypes-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "cloudpcdeviceimage-getsourceimages-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "connector-get-memberof-csharp-Beta-executes", MissingDataKnownIssue },
                { "contenttype-ispublished-csharp-Beta-executes", MissingDataKnownIssue },
                { "convert-item-content-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "drive-root-subscriptions-socketio-csharp-Beta-executes", MissingDataKnownIssue },
                { "event-delta-calendarview-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "event-get-attachments-beta-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-a-count-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-a-count-endswith-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-accesspackageassignmentpolicy-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageassignmentrequest-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageassignmentresourcerole-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageresourceenvironment-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageresourceroles-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageresourceroles2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackagesincompatiblewith-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accessreviewhistorydefinition-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-agentgroups-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-agents-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-alert-csharp-Beta-executes", EphemeralAlertDataKnownIssue },
                { "get-all-roomlists-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-all-rooms-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-allchannelmessages-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-allowedgroups-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-allowedusers-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-and-expand-item-attachment-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-appconsentrequest-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-applications-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-appmanagementpolicy-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-appointments-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-approval-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-approvalstep-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-approvalstep-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-attendeereport-app-token-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-audioroutinggroup-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-audioroutinggroups-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-authenticationmethod-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-azureaddevice-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-b2cauthenticationmethodspolicy-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-b2cuserflow-list-identityproviders-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-b2cuserflow-list-userflowidentityproviders-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-b2cuserflows-apiconnectorconfiguration-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-b2cuserflows-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { $"get-b2xuserflows-apiconnectorconfiguration-csharp-{version}-executes", StructuralPropertiesAreNotHandledKnownIssue},
                { "get-bitlockerrecoverykey-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-bitlockerrecoverykey-2-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-bitlockerrecoverykey-3-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-bitlockerrecoverykey-4-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-bookingappointment-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-bookingbusiness-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-bookingcurrency-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-bookingcustomer-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-bookingservice-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-bookingstaffmember-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-built-in-cloudpc-role-unifiedroledefinition-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-built-in-entitlementmanagement-role-unifiedroledefinition-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-bundle-and-children-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-bundle-metadata-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-call-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-call-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-callrecord-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-callrecord-expanded-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-callrecord-sessions-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-callrecord-sessions-expanded-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-case-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-chat-operation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpc-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcauditevent-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcconnection-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcdevice-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcdeviceimage-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpconpremisesconnection-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpconpremisesconnection-withdetails-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcoverview-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcprovisioningpolicy-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcprovisioningpolicy-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcusersetting-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcusersetting-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-comments-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-conditionalaccesspolicycoverage-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-connection-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-connectionoperation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-connections-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-connector-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-connector-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-connectorgroup-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-connectorgroup-members-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-connectorgroups-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-connectors-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-contract-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-continuousaccessevaluationpolicy-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-credentialuserregistrationssummary-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-custodian-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-custodian-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-customers-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-deleteditems-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-deployment-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-directorysetting-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-directorysettingtemplate-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-document-value-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-educationalactivity-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-educationsubmissionresource-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-educationsynchronizationprofile-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-educationsynchronizationprofile-error-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-educationsynchronizationprofile-status-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-educationsynchronizationprofile-uploadurl-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-emailauthenticationmethod-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-emailauthenticationmethodconfiguration-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-enabled-dynamic-groups-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-endpoint-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-event-based-on-eventmessage-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-event-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-event-in-text-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-event-multiple-locations-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-fido2authenticationmethod-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-fido2authenticationmethodconfiguration-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-file-attachment-beta-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-governanceresources-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-governancerolesetting-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-group-3-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-identityuserflow-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-identityuserflowattributeassignment-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-identityuserflowattributeassignment-3-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-identityuserflowattributeassignment-expand-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-identityuserflowattributeassignment-expand-3-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-incompatiblegroups-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-informationprotectionlabel-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-instances-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-item-attachment-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-serviceplans-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-federatedidentitycredential-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-user-assignments-expand-submissions-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-subjectrightsrequest-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-user-assignments-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-supportedregions-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-devices-by-extensionattribute-csharp-Beta-executes", MissingDataKnownIssue with {GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/570"} },
                { "get-custom-question-csharp-Beta-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/573"} },
                { "list-custom-questions-csharp-Beta-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/573"} },
                { "get-registration-csharp-Beta-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/573"} },
                { "get-subjectrightsrequest-csharp-Beta-executes", NeedsAnalysisKnownIssue with{ GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/574" } },
                { "list-authorednote-csharp-Beta-executes", NeedsAnalysisKnownIssue with{ GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/574" } },
                { "list-registratrants-csharp-Beta-executes", NeedsAnalysisKnownIssue with{ GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/573" } },
                { "subjectrightsrequest-getfinalattachment-csharp-Beta-executes", NeedsAnalysisKnownIssue with{ GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/574" } },
                { "subjectrightsrequest-getfinalreport-csharp-Beta-executes", NeedsAnalysisKnownIssue with{ GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/574" } },
                { "get-federatedidentitycredential-csharp-Beta-executes", MissingDataKnownIssue with{ GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/575" } },
                { "get-workbookcommentreply-csharp-Beta-executes", NeedsAnalysisKnownIssue with{ GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/576" } },

                { "get-itemaddress-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-itememail-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-itempatent-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-itemphone-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-itempublication-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-jobs-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-keysets-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-labels-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-languageproficiency-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-legalhold-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-list-multi-expand-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-mailboxsettings-2-csharp-V1-executes", StructuralPropertiesAreNotHandledKnownIssue },
                { "get-mailboxsettings-3-csharp-V1-executes", StructuralPropertiesAreNotHandledKnownIssue },
                { "get-manageddevicecompliance-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-manageddevicecompliancetrend-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-managementaction-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-managementactiontenantdeploymentstatus-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-managementintent-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-managementtemplate-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-manager-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-meetingattendancereport-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-messagerule-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-microsoftauthenticatorauthenticationmethod-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-microsoftauthenticatorauthenticationmethodconfiguration-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-mobilitymanagementpolicy-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-noncustodialdatasource-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-onenoteoperation-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-onlinemeeting-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-onpremisesagent-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-onpremisesagentgroup-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-onpremisespublishingprofile-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-opentypeextension-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-opentypeextension-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-opentypeextension-4-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-operation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-organizationalbrandingproperties-5-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-organizationalbrandingproperties-6-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-outlooktask-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-outlooktask-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-outlooktaskfolder-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-outlooktaskgroup-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-page-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-participant-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-participants-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-passwordauthenticationmethod-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-passwordlessmicrosoftauthenticatorauthenticationmethod-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-personanniversary-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-personannotation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-personaward-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-personcertification-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-personinterest-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-personname-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-personwebsite-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-phoneauthenticationmethod-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-pivottables-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-plannerroster-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-plannerrostermember-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-plans-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-printer-tasktrigger-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-printershare-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-printoperation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-printsettings-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-printusagebyprinter-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-printusagebyuser-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-privilegedapproval-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-privilegedapproval-2-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedrole-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-privilegedroleassignment-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-privilegedroleassignmentrequest-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedroleassignments-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedroleassignments-2-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedroleassignments-3-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedroleassignments-4-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedroles-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedrolesettings-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-privilegedrolesummary-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-profilecardproperty-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-programcontrol-from-program-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-projectparticipation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-publishedresource-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-publishedresources-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-recording-app-token-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-reference-attachment-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-relation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-relyingpartydetailedsummary-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-replies-2-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-resources-2-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-reviewset-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-reviewsetquery-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-riskdetection-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-riskyuser-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-riskyuser-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-riskyuser-historyitem-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-riskyuser-historyitem-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-roledefinitions-cloudpc-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-rows-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-rubric-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-schema-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-securityaction-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-services-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-set-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-set-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-settings-2-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-settings-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-sitesource-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-sitesource-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-skillproficiency-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-smsauthenticationmethodconfiguration-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-sourcecollection-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-staffmembers-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-subscription-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-synchronizationjob-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-synchronizationschema-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-tablerow-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-tag-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-task-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-taskdefinition-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-taskfolders-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-teamworktag-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-teamworktagmember-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-temporaryaccesspassauthenticationmethod-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-tenant-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-tenantcustomizedinformation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-tenantdetailedinformation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-tenantgroup-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-tenanttag-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-term-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-tiindicator-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-trustframeworkkeyset-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-trustframeworks-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-unifiedgroupsource-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedgroupsource-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleassignment-3-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleassignmentmultiple-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleassignmentschedule-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleassignmentscheduleinstance-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleassignmentschedulerequest-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleeligibilityschedule-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleeligibilityscheduleinstance-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleeligibilityschedulerequest-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedrolemanagementpolicy-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedrolemanagementpolicyassignment-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedrolemanagementpolicyrule-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-updatableasset-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-updatableassetgroup-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-useraccountinformation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-userconsentrequest-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-userflowlanguageconfiguration-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-userflowlanguageconfiguration-3-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-userflowlanguageconfiguration-filter-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-userflowlanguagepage-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-userflowlanguagepage-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-userflowlanguagepage-3-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-userflows-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-userriskhitsory-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-userriskhitsory-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-usersource-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-usersource-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-webaccount-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-windowsdevicemalwarestate-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-windowshelloforbusinessauthenticationmethod-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-windowsprotectionstate-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-workbookcomment-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-workbookoperation-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-workbookpivottable-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-workposition-csharp-Beta-executes", MissingDataKnownIssue },
                { "identityuserflowattributeassignment-getorder-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-addtoreviewsetoperation-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-aggregatedpolicycompliance-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-album-bundles-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-all-bundles-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-appmanagementpolicyappliesto-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-appmanagementpolicyappliesto-select-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-b2cuserflows-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-b2cuserflows-expand-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-caseoperation-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-cloudpcauditevent-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-cloudpcconnection-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-cloudpcdevice-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-cloudpcdeviceimages-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-cloudpconpremisesconnections-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-cloudpcoverview-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-cloudpcprovisioningpolicies-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-cloudpcs-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-cloudpcunifiedroleassignmentmultiple-1-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-cloudpcunifiedroleassignmentmultiple-2-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-cloudpcusersetting-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-conditionalaccesspolicycoverage-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-credentialuserregistrationssummary-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-datasource-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-datasource-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-datasource-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-estimatestatisticsoperation-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-group-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-legalhold-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-manageddevicecompliance-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-managementaction-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-managementactiontenantdeploymentstatus-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-managementintent-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-managementtemplate-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-noncustodialdatasource-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-plannerplan-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-plannerrostermember-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-reviewset-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-reviewsetquery-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-riskdetection-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-riskyuser-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-sitesource-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-sourcecollection-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-tag-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-tag-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-teamworktagmember-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-tenant-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-tenantcustomizedinformation-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-tenantdetailedinformation-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-tenantgroup-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-tenanttag-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-unifiedrolemanagementpolicy-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-unifiedrolemanagementpolicyassignment-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-unifiedrolemanagementpolicyrule-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-updatableasset-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-userconsentrequest-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-usersource-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-windowsdevicemalwarestate-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-windowsprotectionstate-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "outlook-task-get-attachments-csharp-Beta-executes", MissingDataKnownIssue },
                { "outlooktaskfolder-get-tasks-csharp-Beta-executes", MissingDataKnownIssue },
                { "planner-get-tasks-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "privilegedapproval-myrequests-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "privilegedroleassignment-my-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "privilegedroleassignmentrequest-my-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "rbacapplication-rolescheduleinstances-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "rbacapplication-roleschedules-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "search-sites-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "servicehealthissue-incidentreport-csharp-Beta-executes", MissingDataKnownIssue },
                { "synchronizationschema-filteroperators-csharp-Beta-executes", MissingDataKnownIssue },
                { "synchronizationschema-functions-csharp-Beta-executes", MissingDataKnownIssue },
                { "tablerow-range-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "tag-ashierarchy-csharp-Beta-executes", MissingDataKnownIssue },
                { "teamsappicon-get-hostedcontent-coloricon-value-csharp-Beta-executes", MissingDataKnownIssue },
                { "teamsappicon-get-hostedcontentbytes-outlineicon-value-csharp-Beta-executes", MissingDataKnownIssue },
                { "timecard-get-csharp-Beta-executes", MissingDataKnownIssue },
                { "trustframeworkkeyset-getactivekey-csharp-Beta-executes", MissingDataKnownIssue },
                { "user-chat-teamsapps-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "user-get-rooms-from-specific-list-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "user-supportedtimezones-iana-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "virtualendpoint-geteffectivepermissions-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "workbookrange-columnsafter-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-columnsbefore-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsabove-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsbelow-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-visibleview-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "workbookrangeview-range-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "callrecord-getdirectroutingcalls-csharp-Beta-executes", MissingDataKnownIssue},
                { "callrecord-getpstncalls-csharp-Beta-executes", MissingDataKnownIssue},
                { "get-attendance-report-csharp-Beta-executes", MissingDataKnownIssue},
                { "get-attendee-report-csharp-Beta-executes", MissingDataKnownIssue},
                { "get-organizationalbranding-frlocale-bannerlogo-csharp-Beta-executes", MissingDataKnownIssue},
                { "get-simulationreportoverview-csharp-Beta-executes", MissingDataKnownIssue},
                { "get-softwareoathauthenticationmethod-csharp-Beta-executes", MissingDataKnownIssue},
                { "list-externaldomainname-csharp-Beta-executes", MissingDataKnownIssue},
                { "list-usersimulationdetails-csharp-Beta-executes", MissingDataKnownIssue},
                { "manageddevice-getcloudpcremoteactionresults-csharp-Beta-executes", MissingDataKnownIssue},
                { "unifiedroleassignmentschedule-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue},
                { "unifiedroleassignmentscheduleinstance-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue},
                { "unifiedroleassignmentschedulerequest-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue},
                { "unifiedroleeligibilityschedule-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue},
                { "unifiedroleeligibilityscheduleinstance-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue},
                { "unifiedroleeligibilityschedulerequest-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue},
                { "appconsentrequest-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-connectors-3-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-educationuser-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-educationuser-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-mailboxsettings-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-mailboxsettings-2-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-mailboxsettings-4-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-printjob-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-printjob-withdocumentdata-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "user-get-room-lists-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "user-get-rooms-in-tenant-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "userconsentrequest-filterbycurrentuser-csharp-Beta-executes", MissingDataKnownIssue },

                { "get-applicationsignindetailedsummary-csharp-Beta-executes", MissingDataKnownIssue },

                { "enum-lists-csharp-Beta-executes", MissingPermissionScopeKnownIssue },

                { "get-applicationtemplate-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-applicationtemplates-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-calendar-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-calendarpermission-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-chartpoint-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-chartpointscollection-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-chartseries-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-deleteditems-count-csharp-Beta-executes", MissingPermissionScopeKnownIssue},
                { "get-endpoints-2-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-jobs-3-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-messagerules-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-organizationalbrandingproperties-2-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-points-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-printservice-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-printserviceendpoint-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-profilecardproperties-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-regionalandlanguagesettings-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-services-2-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-subscriptions-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-swapshiftschangerequest-1-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-user-presences-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-live-event-recording-csharp-Beta-executes", MissingDataKnownIssue},
                { "get-organizationsettings-csharp-Beta-executes", MissingPermissionScopeKnownIssue},
                { "get-samlorwsfedexternaldomainfederation-csharp-Beta-executes", MissingPermissionScopeKnownIssue},
                { "list-samlorwsfedexternaldomainfederation-csharp-Beta-executes", MissingPermissionScopeKnownIssue},
                { "item-search-all-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-activities-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-conversation-members-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-identityapiconnectors-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "user-get-calendarview-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "user-reminderview-csharp-Beta-executes", MissingPermissionScopeKnownIssue },

                { "get-plans-1-csharp-V1-executes", HTTPKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/microsoft-graph-docs/issues/14686" }},
                { "planner-get-tasks-csharp-V1-executes", HTTPKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/microsoft-graph-docs/issues/14687" } },

                { "get-bitlockerrecoverykey-csharp-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/607" } },
                { "get-bitlockerrecoverykey-key-csharp-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/607" } },

                { "accessreviewinstance-filterbycurrentuser-csharp-V1-executes", SDKFunctionParameterKnownIssue },
                { "accessreviewinstancedecisionitem-filterbycurrentuser-csharp-V1-executes", SDKFunctionParameterKnownIssue },

                { "event-get-attachments-v1-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/610" } },
                { "get-event-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/610" } },
                { "get-event-multiple-locations-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/610" } },
                { "get-instances-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/610" } },

                { "get-alert-csharp-V1-executes", EphemeralAlertDataKnownIssue },

                { "get-appconsentrequest-csharp-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/612" } },
                { "get-userconsentrequest-csharp-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/612" } },
                { "list-userconsentrequest-csharp-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/612" } },
                { "userconsentrequest-filterbycurrentuser-csharp-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/612" } },

                { "get-callrecord-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/320" } },
                { "callrecord-getpstncalls-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/320" } },
                { "get-callrecord-expanded-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/320" } },
                { "get-callrecord-sessions-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/320" } },
                { "get-callrecord-sessions-expanded-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/320" } },
                { "callrecord-getdirectroutingcalls-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/320" } },
                { "get-connectionoperation-csharp-V1-executes", EphemeralOperationDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/692"} },
                { "get-externalgroup-csharp-V1-executes", MissingPermissionScopeKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/693" } },
                { "get-schema-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/617" } },
                { "get-externalconnection-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/617" } },

                { "get-contract-1-csharp-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/322", CustomMessage = "blocked" } },

                { "get-microsoftauthenticatorauthenticationmethod-csharp-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/621" } },

                { "get-onlinemeeting-user-token-csharp-V1-executes", MissingDataOnlineMeetingKnownIssue },
                { "get-attendee-report-csharp-V1-executes", MissingDataOnlineMeetingKnownIssue },

                { "get-printconnector-csharp-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/624" } },

                { "get-printershare-capabilities-csharp-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "get-printershare-csharp-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "list-printjob-2-csharp-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "list-group-csharp-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "list-user-csharp-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },

                { "get-printoperation-csharp-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },

                { "get-printtask-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/779" } },

                { "get-printusagebyprinter-csharp-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },

                { "get-printusagebyuser-csharp-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },

                { "get-windowshelloforbusinessauthenticationmethod-csharp-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/638" } },

                { "list-bitlockerrecoverykey-csharp-V1-executes", new KnownIssue(Category.NeedsAnalysis, "Service requires UserAgent") },
                { "list-bitlockerrecoverykey-filter-deviceid-csharp-V1-executes", new KnownIssue(Category.NeedsAnalysis, "Service requires UserAgent") },

                { "contenttype-ispublished-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/651" } },

                { "get-document-value-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/502" } },
                { "get-printjob-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/502" } },
                { "get-printjob-withdocumentdata-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/502" } },
                { "get-printjob-withtasks-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/502" } },

                { "get-rubric-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/507" } },

                { "user-chat-teamsapps-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/509" } },

                { "get-manager-1-csharp-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/511" } },

                { "get-event-based-on-eventmessage-csharp-V1-executes", new KnownIssue(Category.Documentation, "Delegated permissions don't work as documented", "https://github.com/microsoftgraph/microsoft-graph-docs/issues/15507") },

                { "get-onenoteoperation-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/520" } },

                { "get-workbookoperation-csharp-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/524" } },

                { "get-subjectrightsrequest-csharp-V1-executes", MissingDataSubjectRightsRequestKnownIssue },
                { "list-authorednote-csharp-V1-executes", MissingDataSubjectRightsRequestKnownIssue },
                { "subjectrightsrequest-getfinalattachment-csharp-V1-executes", MissingDataSubjectRightsRequestKnownIssue },
                { "subjectrightsrequest-getfinalreport-csharp-V1-executes", MissingDataSubjectRightsRequestKnownIssue },

                { "drive-root-subscriptions-socketio-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "enum-lists-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-all-roomlists-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-all-rooms-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-and-expand-item-attachment-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-applicationtemplate-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-applicationtemplates-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-calendar-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-calendarpermission-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-call-1-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-call-2-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-comments-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-emailauthenticationmethodconfiguration-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-fido2authenticationmethodconfiguration-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-file-attachment-v1-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-item-attachment-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-messagerule-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-messagerules-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-microsoftauthenticatorauthenticationmethodconfiguration-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-onlinemeeting-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-opentypeextension-1-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-opentypeextension-2-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-opentypeextension-4-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-participant-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-participants-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-pivottables-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-printservice-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-printserviceendpoint-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-printsettings-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-recent-activities-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-reference-attachment-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-replies-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-resources-2-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-rows-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-subscription-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-subscriptions-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-swapshiftschangerequest-1-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-user-presences-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-workbookcomment-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-workbookpivottable-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "item-search-all-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "list-conversation-members-1-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "list-externalconnection-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "list-identityapiconnectors-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "list-printservice-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "list-printserviceendpoint-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "list-subjectrightsrequest-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "user-get-calendarview-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "user-reminderview-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-columnsafter-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-columnsbefore-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsabove-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsabove-nocount-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsbelow-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsbelow-nocount-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-visibleview-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrangeview-range-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-deleteditems-count-csharp-V1-executes", MissingPermissionScopeKnownIssue},
                { "get-organizationalbranding-frlocale-bannerlogo-csharp-V1-executes", MissingPermissionScopeKnownIssue},
                { "get-chartpoint-csharp-V1-executes", ExcelItemAtDocumentationKnownIssue },
                { "get-chartpointscollection-csharp-V1-executes", ExcelItemAtDocumentationKnownIssue },
                { "get-chartseries-csharp-V1-executes", ExcelItemAtDocumentationKnownIssue },
                { "get-points-csharp-V1-executes", ExcelItemAtDocumentationKnownIssue },
                { "get-tablerow-csharp-V1-executes", ExcelItemAtDocumentationKnownIssue },
                { "tablerow-range-csharp-V1-executes", ExcelItemAtDocumentationKnownIssue },
                { "get-educationuser-1-csharp-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "channel-getallchannelmessages-1-csharp-V1-executes", ProtectedAPIKnownIssue },
                { "chat-getallmessages-1-csharp-V1-executes", ProtectedAPIKnownIssue },
                { "accessreviewscheduledefinition-filterbycurrentuser-csharp-V1-executes", SDKFunctionParameterKnownIssue },
                { "appconsentrequest-filterbycurrentuser-csharp-V1-executes", SDKFunctionParameterKnownIssue },
                { "user-supportedtimezones-iana-csharp-V1-executes", SDKFunctionParameterKnownIssue },
                { "get-a-count-csharp-V1-executes", CountIsNotSupportedKnownIssue },
                { "get-a-count-endswith-csharp-V1-executes", CountIsNotSupportedKnownIssue },
                { "get-devices-by-extensionattribute-csharp-V1-executes", CountIsNotSupportedKnownIssue },
                { "get-enabled-dynamic-groups-csharp-V1-executes", CountIsNotSupportedKnownIssue },
                { "list-printconnector-2-csharp-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "list-printershare-2-csharp-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "get-printtasktrigger-csharp-V1-executes", ServiceTaskPrinterKnownIssue },

                { "accesspackage-filterbycurrentuser-csharp-V1-executes", SDKFunctionParameterKnownIssue },
                { "accesspackageassignment-filterbycurrentuser-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "accesspackageassignmentrequest-filterbycurrentuser-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-accesspackageassignmentrequest-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-accesspackagecatalog-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "list-accesspackageassignment-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "list-accesspackageassignmentrequest-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "list-accesspackagecatalog-csharp-V1-executes", MissingPermissionScopeKnownIssue }
            };
    }
}
