using System.Collections.Generic;
using MsGraphSDKSnippetsCompiler.Models;
using static TestsCommon.KnownIssues;

namespace TestsCommon
{
    internal class CSharpKnownIssues
    {
        /// <summary>
        /// Gets known issues
        /// </summary>
        /// <param name="versionEnum">version to get the known issues for</param>
        /// <returns>A mapping of test names into known CSharp issues</returns>
        public static Dictionary<string, KnownIssue> GetCSharpCompilationKnownIssues(Versions versionEnum)
        {
            var version = versionEnum.ToString();
            return new Dictionary<string, KnownIssue>()
            {
                {$"delete-userflowlanguagepage-csharp-{version}-compiles", new KnownIssue(SDK, StreamRequestDoesNotSupportDelete) },
                {$"unfollow-site-csharp-{version}-compiles", new KnownIssue(SDK, "SDK doesn't convert actions defined on collections to methods. https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/250") },
                {$"follow-site-csharp-{version}-compiles", new KnownIssue(SDK, "SDK doesn't convert actions defined on collections to methods. https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/250") },
                { "get-android-count-csharp-V1-compiles", new KnownIssue(SDK, CountIsNotSupported) },
                {$"get-count-group-only-csharp-{version}-compiles", new KnownIssue(SDK, CountIsNotSupported) },
                {$"get-count-only-csharp-{version}-compiles", new KnownIssue(SDK, CountIsNotSupported) },
                {$"get-count-user-only-csharp-{version}-compiles", new KnownIssue(SDK, CountIsNotSupported) },
                {$"get-group-transitivemembers-count-csharp-{version}-compiles", new KnownIssue(SDK, CountIsNotSupported) },
                { "get-transitivereports-csharp-Beta-compiles", new KnownIssue(SDK, CountIsNotSupported)},
                {$"get-user-memberof-count-only-csharp-{version}-compiles", new KnownIssue(SDK, CountIsNotSupported) },
                {$"get-phone-count-csharp-{version}-compiles", new KnownIssue(SDK, SearchHeaderIsNotSupported) },
                {$"get-pr-count-csharp-{version}-compiles", new KnownIssue(SDK, SearchHeaderIsNotSupported) },
                {$"get-team-count-csharp-{version}-compiles", new KnownIssue(SDK, SearchHeaderIsNotSupported) },
                {$"get-tier-count-csharp-{version}-compiles", new KnownIssue(SDK, SearchHeaderIsNotSupported) },
                { "get-video-count-csharp-Beta-compiles", new KnownIssue(SDK, SearchHeaderIsNotSupported) },
                {$"get-wa-count-csharp-{version}-compiles", new KnownIssue(SDK, SearchHeaderIsNotSupported) },
                {$"get-web-count-csharp-{version}-compiles", new KnownIssue(SDK, SearchHeaderIsNotSupported) },
                {$"get-rooms-in-roomlist-csharp-{version}-compiles", new KnownIssue(SDK, "SDK doesn't generate type segment in OData URL. https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_workitems/edit/4997") },
                { "create-externaldomainname-from--csharp-Beta-compiles", new KnownIssue(SDK, TypeCastIsNotSupported)},
                { "list-externaldomainname-csharp-Beta-compiles", new KnownIssue(SDK, TypeCastIsNotSupported)},
                { "list-updatableasset-csharp-Beta-compiles", new KnownIssue(SDK, TypeCastIsNotSupported)},
                { "reportroot-getm365appplatformusercounts-csv-csharp-Beta-compiles", new KnownIssue(SDK, MissingContentProperty) },
                { "reportroot-getm365appplatformusercounts-json-csharp-Beta-compiles", new KnownIssue(SDK, MissingContentProperty) },
                { "reportroot-getm365appusercoundetail-csharp-Beta-compiles", new KnownIssue(SDK, MissingContentProperty) },
                { "reportroot-getm365appusercountdetail-csharp-Beta-compiles", new KnownIssue(SDK, MissingContentProperty) },
                { "reportroot-getm365appusercounts-csv-csharp-Beta-compiles", new KnownIssue(SDK, MissingContentProperty) },
                { "reportroot-getm365appusercounts-json-csharp-Beta-compiles", new KnownIssue(SDK, MissingContentProperty) },
                { "get-transitivereports-user-csharp-Beta-compiles", new KnownIssue(SDK, CountIsNotSupported)},
                { "caseexportoperation-getdownloadurl-csharp-Beta-compiles", new KnownIssue(SDK, TypeCastIsNotSupported) },
                { "remove-rejectedsender-from-group-csharp-V1-compiles", new KnownIssue(SDK, DeleteAsyncIsNotSupportedForReferences) },
                { "delete-acceptedsenders-from-group-csharp-V1-compiles", new KnownIssue(SDK, DeleteAsyncIsNotSupportedForReferences) },
                { "put-b2xuserflows-apiconnectorconfiguration-postattributecollection-csharp-V1-compiles", new KnownIssue(SDK, ComplexTypeNavigationProperties) },
                { "put-b2xuserflows-apiconnectorconfiguration-postfederationsignup-csharp-V1-compiles", new KnownIssue(SDK, ComplexTypeNavigationProperties) },
                { "update-b2xuserflows-userflowidentityprovider-csharp-Beta-compiles", new KnownIssue(SDK, "IB2xIdentityUserFlowUserFlowIdentityProvidersCollectionReferencesRequest' does not contain a definition for 'UpdateAsync'")},
                { "update-b2cuserflows-userflowidentityproviders-csharp-Beta-compiles", new KnownIssue(SDK, "IB2cIdentityUserFlowUserFlowIdentityProvidersCollectionReferencesRequest' does not contain a definition for 'UpdateAsync'")},

                { "deploymentaudience-updateaudience-csharp-Beta-compiles", new KnownIssue(HTTP, "https://github.com/microsoftgraph/microsoft-graph-docs/issues/12811")},
                { "get-devicecompliancepolicysettingstatesummary-csharp-Beta-compiles", new KnownIssue(HTTP, "https://github.com/microsoftgraph/microsoft-graph-docs/issues/13596")},
                { "get-mailboxsettings-4-csharp-Beta-compiles", new KnownIssue(HTTP, "https://github.com/microsoftgraph/microsoft-graph-docs/issues/14238")},
                { "list-administrativeunit-csharp-V1-compiles", new KnownIssue(HTTP, "https://github.com/microsoftgraph/microsoft-graph-docs/issues/12770")},
                { "list-devicecompliancepolicysettingstatesummary-csharp-Beta-compiles", new KnownIssue(HTTP, "https://github.com/microsoftgraph/microsoft-graph-docs/issues/13597")},
                { "update-tenantcustomizedinformation-csharp-Beta-compiles", new KnownIssue(HTTP, "https://github.com/microsoftgraph/microsoft-graph-docs/issues/13556")},
                { "update-accessreviewscheduledefinition-csharp-Beta-compiles", new KnownIssue(HTTP, "https://github.com/microsoftgraph/microsoft-graph-docs/issues/14712")},
                { "update-appleidentityprovider-csharp-Beta-compiles", new KnownIssue(HTTP, "https://github.com/microsoftgraph/microsoft-graph-docs/issues/14713")},

                { "put-b2cuserflows-apiconnectorconfiguration-postfederationsignup-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, StructuralPropertiesAreNotHandled) },
                { "put-b2xuserflows-apiconnectorconfiguration-postfederationsignup-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, StructuralPropertiesAreNotHandled) },
                { "put-b2xuserflows-apiconnectorconfiguration-postattributecollection-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, StructuralPropertiesAreNotHandled) },
                { "put-b2cuserflows-apiconnectorconfiguration-postattributecollection-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, StructuralPropertiesAreNotHandled) },
                { "create-datasource-from--1-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, NamespaceOdataTypeAnnotationsWithoutHashSymbol)},
                { "create-deployment-from--csharp-Beta-compiles", new KnownIssue(SnippetGeneration, NamespaceOdataTypeAnnotationsWithoutHashSymbol)},
                { "create-noncustodialdatasource-from--csharp-Beta-compiles", new KnownIssue(SnippetGeneration, NamespaceOdataTypeAnnotationsWithoutHashSymbol) },
                { "create-noncustodialdatasource-from-email-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, NamespaceOdataTypeAnnotationsWithoutHashSymbol)},
                { "create-noncustodialdatasource-from-siteurl-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, NamespaceOdataTypeAnnotationsWithoutHashSymbol)},
                { $"create-schema-from-connection-async-csharp-{version}-compiles", new KnownIssue(SnippetGeneration, SnippetGenerationCreateAsyncSupport) },
                { "get-endpoints-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, SameBlockNames) },
                { "update-deployment-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, NamespaceOdataTypeAnnotationsWithoutHashSymbol)},
                { "update-deployment-1-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, NamespaceOdataTypeAnnotationsWithoutHashSymbol)},
                { "update-deployment-2-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, NamespaceOdataTypeAnnotationsWithoutHashSymbol)},
                { "reports-getuserarchivedprintjobs-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, DateTimeOffsetHandlingInUrls)},
                { "reports-getprinterarchivedprintjobs-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, DateTimeOffsetHandlingInUrls)},
                { "reports-getgrouparchivedprintjobs-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, DateTimeOffsetHandlingInUrls)},
                { "post-channelmessage-2-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, IdentitySetAndIdentityShouldNestAdditionalData)},
                { "post-chatmessage-2-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, IdentitySetAndIdentityShouldNestAdditionalData)},
                { "post-channelmessage-3-csharp-Beta-compiles", new KnownIssue(SnippetGeneration, IdentitySetAndIdentityShouldNestAdditionalData)},
                { "post-channelmessage-3-csharp-V1-compiles", new KnownIssue(SnippetGeneration, IdentitySetAndIdentityShouldNestAdditionalData)},
                { "post-channelmessage-2-csharp-V1-compiles", new KnownIssue(SnippetGeneration, IdentitySetAndIdentityShouldNestAdditionalData)},
                { "post-chatmessage-2-csharp-V1-compiles", new KnownIssue(SnippetGeneration, IdentitySetAndIdentityShouldNestAdditionalData)},
                { "shift-put-csharp-V1-compiles", new KnownIssue(SnippetGeneration, IdentitySetAndIdentityShouldNestAdditionalData)},

                { "create-educationrubric-from-educationassignment-csharp-V1-compiles", new KnownIssue(Metadata, EducationAssignmentRubricContainsTargetPreprocessor)},
                { "create-directorysetting-from-settings-for-guests-csharp-Beta-compiles", new KnownIssue(Metadata, "GroupSetting undefined in metadata")},
                { "delete-educationrubric-from-educationassignment-csharp-V1-compiles", new KnownIssue(Metadata, EducationAssignmentRubricContainsTargetPreprocessor)},
                { "add-educationcategory-to-educationassignment-csharp-V1-compiles", new KnownIssue(Metadata, EducationAssignmentRubricContainsTargetPreprocessor)},

                { $"event-accept-csharp-{version}-compiles", new KnownIssue(MetadataPreprocessing, EventActionsShouldNotBeReordered) },
                { $"event-decline-csharp-{version}-compiles", new KnownIssue(MetadataPreprocessing, EventActionsShouldNotBeReordered) },
                { $"event-tentativelyaccept-csharp-{version}-compiles", new KnownIssue(MetadataPreprocessing, EventActionsShouldNotBeReordered) },
                { $"create-homerealmdiscoverypolicy-from-serviceprincipal-csharp-Beta-compiles", new KnownIssue(HTTP, RefNeeded) },
                { $"create-certificatebasedauthconfiguration-from-certificatebasedauthconfiguration-csharp-{version}-compiles", new KnownIssue(HTTP, RefNeeded + "\n https://github.com/microsoftgraph/microsoft-graph-docs/issues/14004") },
                { $"create-tokenlifetimepolicy-from-application-csharp-Beta-compiles", new KnownIssue(HTTP, RefNeeded) },

                { "update-accessreviewscheduledefinition-csharp-V1-compiles", NeedsAnalysisKnownIssue},
                { "team-put-schedule-2-csharp-Beta-compiles", NeedsAnalysisKnownIssue},
                { "add-incompatibleaccesspackage-to-accesspackage-csharp-Beta-compiles", NeedsAnalysisKnownIssue},
                { "create-datasource-from--2-csharp-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-directoryobject-from-orgcontact-1-csharp-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-directoryobject-from-orgcontact-2-csharp-Beta-compiles", NeedsAnalysisKnownIssue },
                { "directoryobject-delta-2-csharp-Beta-compiles", NeedsAnalysisKnownIssue },
                { "recent-notebooks-csharp-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-csharp-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-connectorgroup-from-connector-csharp-Beta-compiles", NeedsAnalysisKnownIssue },
                { "set-presence-csharp-V1-compiles", NeedsAnalysisKnownIssue },
                { "clear--presence-csharp-V1-compiles", NeedsAnalysisKnownIssue },
            };
        }

        /// <summary>
        /// Gets execution known issues
        /// </summary>
        /// <param name="versionEnum">version to get the execution known issues for</param>
        /// <returns>A mapping of test names into known CSharp issues</returns>
        public static Dictionary<string, KnownIssue> GetCSharpExecutionKnownIssues(Versions versionEnum)
        {
            var version = versionEnum.ToString();
            return new Dictionary<string, KnownIssue>()
            {
                { "accesspackageassignment-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "accesspackageassignmentrequest-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "accessreviewinstance-filterbycurrentuser-csharp-Beta-executes", MissingDataKnownIssue },
                { "accessreviewinstancedecisionitem-filterbycurrentuser-csharp-Beta-executes", MissingDataKnownIssue },
                { "accessreviewscheduledefinition-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "authenticationmethodsroot-usersregisteredbyfeature-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "authenticationmethodsroot-usersregisteredbymethod-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "bookingbusiness-getcalendarview-csharp-Beta-executes", MissingDataKnownIssue },
                { "cloudpcauditevent-getauditactivitytypes-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "cloudpcdeviceimage-getsourceimages-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "connectedorganization-get-externalsponsors-csharp-Beta-executes", MissingDataKnownIssue },
                { "connectedorganization-get-internalsponsors-csharp-Beta-executes", MissingDataKnownIssue },
                { "connector-get-memberof-csharp-Beta-executes", MissingDataKnownIssue },
                { "contenttype-ispublished-csharp-Beta-executes", MissingDataKnownIssue },
                { "convert-item-content-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "drive-root-subscriptions-socketio-csharp-Beta-executes", MissingDataKnownIssue },
                { "educationschool-get-administrativeunit-csharp-Beta-executes", MissingDataKnownIssue },
                { "educationschool-get-users-csharp-Beta-executes", MissingDataKnownIssue },
                { "event-delta-calendarview-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "event-get-attachments-beta-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-a-count-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-a-count-endswith-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-accesspackage-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageassignmentpolicy-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageassignmentrequest-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageassignmentresourcerole-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackagecatalog-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageresourceenvironment-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageresourceroles-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageresourceroles2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageresourcerolescopes-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageresources-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackagesincompatiblewith-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accessreview-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accessreview-decisions-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accessreview-decisions-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accessreview-reviewers-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accessreviewhistorydefinition-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accessreviewinstance-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accessreviewinstancedecisionitem-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-accessreviewscheduledefinition-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-administrativeunit-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-agentgroups-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-agents-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-alert-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-all-roomlists-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-all-rooms-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-allchannelmessages-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-allowedgroups-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-allowedusers-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-and-expand-item-attachment-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-appconsentrequest-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-applications-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-appmanagementpolicy-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-appointments-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-approval-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-approvalstep-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-approvalstep-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-assignments-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-attendeereport-app-token-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-audioroutinggroup-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-audioroutinggroups-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-authenticationmethod-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-azureaddevice-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-b2cauthenticationmethodspolicy-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-b2cuserflow-list-identityproviders-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-b2cuserflow-list-userflowidentityproviders-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-b2cuserflows-apiconnectorconfiguration-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-b2cuserflows-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-b2xuserflow-list-identityproviders-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-b2xuserflow-list-userflowidentityproviders-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-b2xuserflows-apiconnectorconfiguration-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-b2xuserflows-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-bitlockerrecoverykey-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-bitlockerrecoverykey-2-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-bitlockerrecoverykey-3-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-bitlockerrecoverykey-4-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-bookingappointment-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-bookingbusiness-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-bookingcurrency-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-bookingcustomer-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-bookingservice-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-bookingstaffmember-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-built-in-cloudpc-role-unifiedroledefinition-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-built-in-entitlementmanagement-role-unifiedroledefinition-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-built-in-role-unifiedroledefinition-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-bundle-and-children-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-bundle-metadata-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-call-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-call-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-callrecord-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-callrecord-expanded-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-callrecord-sessions-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-callrecord-sessions-expanded-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-case-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-chartlineformat-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-chat-operation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-chatmessagechannel-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-chatmessagechannel-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-chatmessagechannel-3-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-class-category-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-classes-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpc-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcauditevent-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcconnection-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcdevice-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcdeviceimage-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpconpremisesconnection-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpconpremisesconnection-withdetails-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcoverview-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcprovisioningpolicy-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcprovisioningpolicy-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcusersetting-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcusersetting-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-column-from-contenttype-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-columns-from-contenttype-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-comments-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-conditionalaccesspolicycoverage-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-connectedorganization-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-connection-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-connectionoperation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-connections-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-connector-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-connector-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-connectorgroup-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-connectorgroup-members-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-connectorgroups-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-connectors-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-contact-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-contenttype-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-contract-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-continuousaccessevaluationpolicy-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-countrynamedlocation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-credentialuserregistrationssummary-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-custodian-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-custodian-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-custom-role-unifiedroledefinition-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-customers-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-datapolicyoperation-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-deleteditems-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-deployment-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-directory-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-directorysetting-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-directorysettingtemplate-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-document-value-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-educationalactivity-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-educationassignmentresource-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-educationrubric-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-educationschool-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-educationsubmissionresource-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-educationsynchronizationprofile-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-educationsynchronizationprofile-error-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-educationsynchronizationprofile-status-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-educationsynchronizationprofile-uploadurl-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-emailauthenticationmethod-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-emailauthenticationmethodconfiguration-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-enabled-dynamic-groups-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-endpoint-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-event-based-on-eventmessage-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-event-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-event-in-text-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-event-multiple-locations-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-fido2authenticationmethod-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-fido2authenticationmethodconfiguration-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-file-attachment-beta-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-governanceresources-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-governancerolesetting-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-group-3-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-group-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-hostedcontentchatmessage-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-hostedcontentchatmessage-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-hostedcontentschannelmessage-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-hostedcontentschannelmessage-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-hostedcontentschatmessage-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-identityapiconnector-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-identityuserflow-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-identityuserflowattributeassignment-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-identityuserflowattributeassignment-2-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-identityuserflowattributeassignment-3-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-identityuserflowattributeassignment-expand-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-identityuserflowattributeassignment-expand-2-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-identityuserflowattributeassignment-expand-3-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-incompatiblegroups-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-informationprotectionlabel-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-inheritsfrom-unifiedroledefinition-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-instances-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-ipnamedlocation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-item-attachment-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-item-delta-last-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-itemaddress-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-itememail-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-itempatent-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-itemphone-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-itempublication-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-jobs-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-keysets-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-labels-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-languageproficiency-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-legalhold-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-list-multi-expand-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-listmessagereplies-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-manageddevicecompliance-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-manageddevicecompliancetrend-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-managementaction-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-managementactiontenantdeploymentstatus-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-managementintent-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-managementtemplate-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-manager-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-meetingattendancereport-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-messagerule-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-microsoftauthenticatorauthenticationmethod-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-microsoftauthenticatorauthenticationmethodconfiguration-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-mobilitymanagementpolicy-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-namedlocation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-noncustodialdatasource-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-oauth2permissiongrant-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-one-thumbnail-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-onenoteoperation-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-onlinemeeting-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-onpremisesagent-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-onpremisesagentgroup-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-onpremisespublishingprofile-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-opentypeextension-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-opentypeextension-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-opentypeextension-4-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-operation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-organizationalbrandingproperties-5-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-organizationalbrandingproperties-6-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-outlooktask-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-outlooktask-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-outlooktaskfolder-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-outlooktaskgroup-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-page-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-participant-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-participants-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-passwordauthenticationmethod-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-passwordlessmicrosoftauthenticatorauthenticationmethod-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-permission-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-personanniversary-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-personannotation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-personaward-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-personcertification-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-personinterest-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-personname-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-personwebsite-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-phoneauthenticationmethod-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-pivottables-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-plannerroster-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-plannerrostermember-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-plans-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-printer-tasktrigger-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-printershare-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-printoperation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-printsettings-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-printtaskdefinition-tasks-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-printusagebyprinter-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-printusagebyuser-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-privilegedapproval-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-privilegedapproval-2-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedrole-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-privilegedroleassignment-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-privilegedroleassignmentrequest-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedroleassignments-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedroleassignments-2-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedroleassignments-3-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedroleassignments-4-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedroles-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedrolesettings-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-privilegedrolesummary-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-profilecardproperty-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-programcontrol-from-program-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-projectparticipation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-publishedresource-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-publishedresources-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-recording-app-token-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-reference-attachment-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-registeredowners-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-registeredusers-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-relation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-relyingpartydetailedsummary-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-replies-2-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-resources-2-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-reviewset-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-reviewsetquery-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-riskdetection-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-riskyuser-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-riskyuser-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-riskyuser-historyitem-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-riskyuser-historyitem-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-roleassignments-2-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-roledefinitions-cloudpc-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-rows-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-rubric-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-schema-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-scopedrolemember-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-scopedrolemember-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-sectiongroup-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-sectiongroups-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-securityaction-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-servicehealth-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-servicehealth-with-issues-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-servicehealthissue-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-services-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-serviceupdatemessage-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-set-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-set-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-settings-2-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-settings-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-shared-driveitem-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-shared-driveitem-expand-children-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-shared-root-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-sitecollection-termstore-set-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-sitesource-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-sitesource-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-skillproficiency-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-smsauthenticationmethodconfiguration-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-sourcecollection-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-staffmembers-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-subscription-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-synchronizationjob-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-synchronizationschema-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-tablerow-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-tag-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-task-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-taskdefinition-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-taskfolders-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-teamsappicon-coloricon-customapp-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-teamsappicon-outlineicon-customapp-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-teamsappicon-outlineicon-publicapp-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-teamworkbot-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-teamworktag-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-teamworktagmember-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-temporaryaccesspassauthenticationmethod-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-tenant-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-tenantcustomizedinformation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-tenantdetailedinformation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-tenantgroup-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-tenanttag-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-term-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-term-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-thumbnail-content-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-thumbnail-custom-size-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-tiindicator-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-trustframeworkkeyset-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-trustframeworks-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-unifiedgroupsource-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedgroupsource-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleassignment-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleassignment-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleassignment-3-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleassignmentmultiple-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleassignmentschedule-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleassignmentscheduleinstance-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleassignmentschedulerequest-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleeligibilityschedule-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleeligibilityscheduleinstance-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleeligibilityschedulerequest-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedrolemanagementpolicy-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedrolemanagementpolicyassignment-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedrolemanagementpolicyrule-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-updatableasset-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-updatableassetgroup-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-useraccountinformation-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-userconsentrequest-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-userflowattributes-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-userflowlanguageconfiguration-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-userflowlanguageconfiguration-2-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-userflowlanguageconfiguration-3-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-userflowlanguageconfiguration-filter-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-userflowlanguagepage-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-userflowlanguagepage-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-userflowlanguagepage-3-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-userflows-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-userriskhitsory-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-userriskhitsory-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-usersource-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-usersource-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-webaccount-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-windowsdevicemalwarestate-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-windowshelloforbusinessauthenticationmethod-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-windowsprotectionstate-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-workbookcomment-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-workbookcommentreply-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-workbookoperation-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-workbookpivottable-csharp-Beta-executes", MissingDataKnownIssue },
                { "get-workposition-csharp-Beta-executes", MissingDataKnownIssue },
                { "identityuserflowattributeassignment-getorder-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-accessreviewinstance-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-accessreviewinstancedecisionitem-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-accessreviewinstancedecisionitem-pendingapproval-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-addtoreviewsetoperation-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-aggregatedpolicycompliance-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-album-bundles-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-all-bundles-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-appmanagementpolicyappliesto-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-appmanagementpolicyappliesto-select-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-b2cuserflows-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-b2cuserflows-expand-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-caseoperation-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-cloudpcauditevent-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-cloudpcconnection-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-cloudpcdevice-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-cloudpcdeviceimages-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-cloudpconpremisesconnections-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-cloudpcoverview-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-cloudpcprovisioningpolicies-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-cloudpcs-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-cloudpcunifiedroleassignmentmultiple-1-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-cloudpcunifiedroleassignmentmultiple-2-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-cloudpcusersetting-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-conditionalaccesspolicycoverage-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-credentialuserregistrationssummary-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-datasource-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-datasource-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-datasource-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-estimatestatisticsoperation-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-group-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-legalhold-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-manageddevicecompliance-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-managementaction-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-managementactiontenantdeploymentstatus-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-managementintent-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-managementtemplate-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-noncustodialdatasource-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-plannerplan-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-plannerrostermember-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-reviewset-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-reviewsetquery-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-riskdetection-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-riskyuser-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-sitesource-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-sourcecollection-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-tag-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-tag-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-teamworktagmember-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-tenant-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-tenantcustomizedinformation-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-tenantdetailedinformation-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-tenantgroup-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-tenanttag-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-unifiedrolemanagementpolicy-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-unifiedrolemanagementpolicyassignment-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-unifiedrolemanagementpolicyrule-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-updatableasset-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-usageright-1-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-usageright-2-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-userconsentrequest-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-usersource-csharp-Beta-executes", MissingDataKnownIssue },
                { "list-windowsdevicemalwarestate-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-windowsprotectionstate-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "outlook-task-get-attachments-csharp-Beta-executes", MissingDataKnownIssue },
                { "outlooktaskfolder-get-tasks-csharp-Beta-executes", MissingDataKnownIssue },
                { "planner-get-tasks-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "privilegedapproval-myrequests-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "privilegedroleassignment-my-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "privilegedroleassignmentrequest-my-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "range-usedrange-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "rbacapplication-rolescheduleinstances-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "rbacapplication-roleschedules-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "search-sites-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "sectiongroup-get-sections-csharp-Beta-executes", MissingDataKnownIssue },
                { "servicehealthissue-incidentreport-csharp-Beta-executes", MissingDataKnownIssue },
                { "site-getapplicablecontenttypesforlist-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "synchronizationschema-filteroperators-csharp-Beta-executes", MissingDataKnownIssue },
                { "synchronizationschema-functions-csharp-Beta-executes", MissingDataKnownIssue },
                { "table-totalrowrange-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "tablecolumn-totalrowrange-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "tablerow-range-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "tag-ashierarchy-csharp-Beta-executes", MissingDataKnownIssue },
                { "teamsappicon-get-hostedcontent-coloricon-value-csharp-Beta-executes", MissingDataKnownIssue },
                { "teamsappicon-get-hostedcontentbytes-outlineicon-value-csharp-Beta-executes", MissingDataKnownIssue },
                { "timecard-get-csharp-Beta-executes", MissingDataKnownIssue },
                { "trustframeworkkeyset-getactivekey-csharp-Beta-executes", MissingDataKnownIssue },
                { "user-chat-teamsapps-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "user-get-rooms-from-specific-list-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "user-supportedtimezones-iana-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "virtualendpoint-geteffectivepermissions-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "workbookrange-columnsafter-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-columnsbefore-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsabove-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsbelow-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-visibleview-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "workbookrangeview-range-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-educationuser-2-csharp-Beta-executes", NeedsAnalysisKnownIssue },

                { "accessreviewinstance-filterbycurrentuser-csharp-V1-executes", MissingDataKnownIssue },
                { "accessreviewinstancedecisionitem-filterbycurrentuser-csharp-V1-executes", MissingDataKnownIssue },
                { "accessreviewscheduledefinition-filterbycurrentuser-csharp-V1-executes", SDKFunctionParameterKnownIssue },
                { "appconsentrequest-filterbycurrentuser-csharp-V1-executes", SDKFunctionParameterKnownIssue },
                { "callrecord-getdirectroutingcalls-csharp-Beta-executes", MissingDataKnownIssue},
                { "callrecord-getpstncalls-csharp-Beta-executes", MissingDataKnownIssue},
                { "drive-root-subscriptions-socketio-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "educationschool-get-users-csharp-V1-executes", MissingDataKnownIssue },
                { "event-get-attachments-v1-csharp-V1-executes", MissingDataKnownIssue },
                { "get-a-count-csharp-V1-executes", SDKMissingCountSupportKnownIssue },
                { "get-a-count-endswith-csharp-V1-executes", SDKMissingCountSupportKnownIssue },
                { "get-accessreviewinstance-csharp-V1-executes", MissingDataKnownIssue },
                { "get-accessreviewinstancedecisionitem-csharp-V1-executes", MissingDataKnownIssue },
                { "get-accessreviewscheduledefinition-csharp-V1-executes", MissingDataKnownIssue },
                { "get-administrativeunit-csharp-V1-executes", MissingDataKnownIssue },
                { "get-alert-csharp-V1-executes", MissingDataKnownIssue },
                { "get-all-roomlists-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-all-rooms-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-and-expand-item-attachment-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-appconsentrequest-csharp-V1-executes", MissingDataKnownIssue },
                { "get-attendance-report-csharp-Beta-executes", MissingDataKnownIssue},
                { "get-attendee-report-csharp-Beta-executes", MissingDataKnownIssue},
                { "get-organizationalbranding-frlocale-bannerlogo-csharp-Beta-executes", MissingDataKnownIssue},
                { "get-simulationreportoverview-csharp-Beta-executes", MissingDataKnownIssue},
                { "get-softwareoathauthenticationmethod-csharp-Beta-executes", MissingDataKnownIssue},
                { "get-b2xuserflow-list-identityproviders-csharp-V1-executes", MissingDataKnownIssue },
                { "get-b2xuserflows-apiconnectorconfiguration-csharp-V1-executes", MissingDataKnownIssue },
                { "get-b2xuserflows-csharp-V1-executes", MissingDataKnownIssue },
                { "get-call-1-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-call-2-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-callrecord-csharp-V1-executes", MissingDataKnownIssue },
                { "get-callrecord-expanded-csharp-V1-executes", MissingDataKnownIssue },
                { "get-callrecord-sessions-csharp-V1-executes", MissingDataKnownIssue },
                { "get-callrecord-sessions-expanded-csharp-V1-executes", MissingDataKnownIssue },
                { "get-chartlineformat-csharp-V1-executes", MissingDataKnownIssue },
                { "get-classes-2-csharp-V1-executes", MissingDataKnownIssue },
                { "get-comments-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-connectionoperation-csharp-V1-executes", MissingDataKnownIssue },
                { "get-contact-csharp-V1-executes", MissingDataKnownIssue with { Message = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/517" } },
                { "get-contract-1-csharp-V1-executes", MissingDataKnownIssue },
                { "get-countrynamedlocation-csharp-V1-executes", MissingDataKnownIssue },
                { "get-directory-csharp-V1-executes", MissingDataKnownIssue with { Message = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/513" } },
                { "get-document-value-csharp-V1-executes", MissingDataKnownIssue with { Message = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/502" } },
                { "get-educationassignmentresource-csharp-V1-executes", MissingDataKnownIssue },
                { "get-educationrubric-csharp-V1-executes", MissingDataKnownIssue },
                { "get-educationschool-csharp-V1-executes", MissingDataKnownIssue },
                { "get-educationsubmissionresource-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "get-emailauthenticationmethodconfiguration-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-event-based-on-eventmessage-csharp-V1-executes", MissingDataKnownIssue with { Message = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/518" } },
                { "get-event-csharp-V1-executes", MissingDataKnownIssue },
                { "get-event-multiple-locations-csharp-V1-executes", MissingDataKnownIssue },
                { "get-externalconnection-csharp-V1-executes", MissingDataKnownIssue },
                { "callrecord-getdirectroutingcalls-csharp-V1-executes", MissingDataKnownIssue},
                { "callrecord-getpstncalls-csharp-V1-executes", MissingDataKnownIssue},
                { "contenttype-ispublished-csharp-V1-executes", MissingDataKnownIssue},
                { "get-chatmessagechannel-1-csharp-V1-executes", MissingDataKnownIssue },
                { "get-chatmessagechannel-2-csharp-V1-executes", MissingDataKnownIssue },
                { "get-chatmessagechannel-3-csharp-V1-executes", MissingDataKnownIssue },
                { "get-class-category-csharp-V1-executes", MissingDataKnownIssue },
                { "get-roleassignments-2-csharp-V1-executes", MissingDataKnownIssue},
                { "get-hostedcontentchatmessage-1-csharp-V1-executes", MissingDataKnownIssue },
                { "get-hostedcontentchatmessage-2-csharp-V1-executes", MissingDataKnownIssue },
                { "get-hostedcontentschannelmessage-1-csharp-V1-executes", MissingDataKnownIssue },
                { "get-hostedcontentschannelmessage-2-csharp-V1-executes", MissingDataKnownIssue },
                { "get-hostedcontentschatmessage-1-csharp-V1-executes", MissingDataKnownIssue },
                { "get-identityapiconnector-csharp-V1-executes", MissingDataKnownIssue },
                { "get-identityuserflowattributeassignment-3-csharp-V1-executes", MissingDataKnownIssue },
                { "get-identityuserflowattributeassignment-expand-3-csharp-V1-executes", MissingDataKnownIssue },
                { "get-instances-csharp-V1-executes", MissingDataKnownIssue },
                { "get-ipnamedlocation-csharp-V1-executes", MissingDataKnownIssue },
                { "get-item-attachment-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-listmessagereplies-1-csharp-V1-executes", MissingDataKnownIssue },
                { "list-externaldomainname-csharp-Beta-executes", MissingDataKnownIssue},
                { "list-usersimulationdetails-csharp-Beta-executes", MissingDataKnownIssue},
                { "manageddevice-getcloudpcremoteactionresults-csharp-Beta-executes", MissingDataKnownIssue},
                { "get-fido2authenticationmethodconfiguration-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-file-attachment-v1-csharp-V1-executes", MissingPermissionScopeKnownIssue },

                { "get-identityuserflowattributeassignment-2-csharp-V1-executes", MissingDataKnownIssue },
                { "get-identityuserflowattributeassignment-expand-2-csharp-V1-executes", MissingDataKnownIssue },
                { "get-item-delta-last-csharp-V1-executes", MissingDataKnownIssue with { Message = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/519" } },
                { "get-manager-1-csharp-V1-executes", MissingDataKnownIssue with { Message = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/511" } },
                { "get-messagerule-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-microsoftauthenticatorauthenticationmethod-csharp-V1-executes", MissingDataKnownIssue },
                { "get-microsoftauthenticatorauthenticationmethodconfiguration-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-namedlocation-csharp-V1-executes", MissingDataKnownIssue },
                { "get-oauth2permissiongrant-csharp-V1-executes", MissingDataKnownIssue },
                { "get-one-thumbnail-csharp-V1-executes", SnippetGenerationKnownIssue with { Message = "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/744" } },
                { "get-onenoteoperation-csharp-V1-executes", MissingDataKnownIssue with { Message = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/520" } },
                { "get-onlinemeeting-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-onlinemeeting-user-token-csharp-V1-executes", MissingDataKnownIssue },
                { "get-opentypeextension-1-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-opentypeextension-2-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-opentypeextension-4-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-organizationalbrandingproperties-5-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "get-organizationalbrandingproperties-6-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "get-participant-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-participants-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-permission-csharp-V1-executes", MissingDataKnownIssue },
                { "get-pivottables-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-plans-1-csharp-V1-executes", HTTPKnownIssue with { Message = "https://github.com/microsoftgraph/microsoft-graph-docs/issues/14686" }},
                { "get-printconnector-csharp-V1-executes", MissingDataKnownIssue },
                { "get-printershare-capabilities-csharp-V1-executes", MissingDataKnownIssue },
                { "get-printershare-csharp-V1-executes", MissingDataKnownIssue },
                { "get-printoperation-csharp-V1-executes", MissingDataKnownIssue },
                { "get-printsettings-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-printtask-csharp-V1-executes", MissingDataKnownIssue },
                { "get-printtaskdefinition-csharp-V1-executes", MissingDataKnownIssue },
                { "get-printtasktrigger-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "get-printusagebyprinter-csharp-V1-executes", MissingDataKnownIssue },
                { "get-printusagebyuser-csharp-V1-executes", MissingDataKnownIssue },
                { "get-recent-activities-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-reference-attachment-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-replies-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-resources-2-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-rows-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-rubric-csharp-V1-executes", MissingDataKnownIssue with { Message = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/507" } },
                { "get-scopedrolemember-1-csharp-V1-executes", MissingDataKnownIssue },
                { "get-scopedrolemember-2-csharp-V1-executes", MissingDataKnownIssue },
                { "get-sectiongroup-csharp-V1-executes", MissingDataKnownIssue },
                { "get-sectiongroups-csharp-V1-executes", MissingDataKnownIssue },
                { "get-schema-csharp-V1-executes", MissingDataKnownIssue },
                { "get-servicehealth-csharp-V1-executes", MissingDataKnownIssue },
                { "get-servicehealth-with-issues-csharp-V1-executes", MissingDataKnownIssue },
                { "get-servicehealthissue-csharp-V1-executes", MissingDataKnownIssue },
                { "get-serviceupdatemessage-csharp-V1-executes", MissingDataKnownIssue },
                { "get-column-from-contenttype-csharp-V1-executes", MissingDataKnownIssue},
                { "get-columns-from-contenttype-csharp-V1-executes", MissingDataKnownIssue},
                { "get-contenttype-csharp-V1-executes", MissingDataKnownIssue},
                { "get-externalgroup-csharp-V1-executes", MissingDataKnownIssue},
                { "get-group-3-csharp-V1-executes", MissingDataKnownIssue},
                { "get-relation-csharp-V1-executes", MissingDataKnownIssue},
                { "get-set-2-csharp-V1-executes", MissingDataKnownIssue},
                { "get-term-1-csharp-V1-executes", MissingDataKnownIssue},
                { "get-term-2-csharp-V1-executes", MissingDataKnownIssue},
                { "get-userflowlanguageconfiguration-3-csharp-V1-executes", MissingDataKnownIssue },
                { "get-userflowattributes-csharp-V1-executes", MissingDataKnownIssue },
                { "get-userflowlanguagepage-2-csharp-V1-executes", MissingDataKnownIssue },
                { "get-userflowlanguagepage-3-csharp-V1-executes", MissingDataKnownIssue },
                { "list-accessreviewinstance-csharp-V1-executes", MissingDataKnownIssue },
                { "list-accessreviewinstancedecisionitem-csharp-V1-executes", MissingDataKnownIssue },
                { "site-getapplicablecontenttypesforlist-csharp-V1-executes", MissingDataKnownIssue},

                { "get-subscription-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-tablerow-csharp-V1-executes", PermissionsExcelIdKnownIssue },
                { "get-teamworkbot-csharp-V1-executes", MissingDataKnownIssue },
                { "get-thumbnail-content-csharp-V1-executes", SnippetGenerationKnownIssue with { Message = "https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/744" } },
                { "get-userconsentrequest-csharp-V1-executes", MissingDataKnownIssue },
                { "get-userflowlanguageconfiguration-2-csharp-V1-executes", MissingDataKnownIssue },
                { "get-built-in-role-unifiedroledefinition-csharp-V1-executes", MissingDataKnownIssue},
                { "get-unifiedroleassignment-csharp-V1-executes", MissingDataKnownIssue},
                { "get-custom-role-unifiedroledefinition-csharp-V1-executes", MissingDataKnownIssue},
                { "get-inheritsfrom-unifiedroledefinition-csharp-V1-executes", MissingDataKnownIssue},
                { "get-windowshelloforbusinessauthenticationmethod-csharp-V1-executes", MissingDataKnownIssue },
                { "get-workbookcomment-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-workbookcommentreply-csharp-V1-executes", HTTPKnownIssue with { Message = "https://github.com/microsoftgraph/microsoft-graph-docs/issues/14702" } },
                { "get-workbookoperation-csharp-V1-executes", MissingDataKnownIssue with { Message = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/524" } },
                { "get-workbookpivottable-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "identityuserflowattributeassignment-getorder-csharp-V1-executes", MissingDataKnownIssue },
                { "list-externalconnection-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "list-group-csharp-V1-executes", MissingDataKnownIssue },
                { "list-printjob-2-csharp-V1-executes", MissingDataKnownIssue },
                { "list-printtask-csharp-V1-executes", MissingDataKnownIssue },
                { "list-user-csharp-V1-executes", MissingDataKnownIssue },
                { "list-userconsentrequest-csharp-V1-executes", MissingDataKnownIssue },
                { "planner-get-tasks-csharp-V1-executes", HTTPKnownIssue with { Message = "https://github.com/microsoftgraph/microsoft-graph-docs/issues/14687" } },
                { "range-usedrange-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "range-usedrange-valuesonly-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "sectionsgroup-get-sections-csharp-V1-executes", MissingDataKnownIssue },
                { "servicehealthissue-incidentreport-csharp-V1-executes", MissingDataKnownIssue },
                { "table-totalrowrange-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "tablecolumn-totalrowrange-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "tablerow-range-csharp-V1-executes", PermissionsExcelIdKnownIssue },
                { "unifiedroleassignmentschedule-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue},
                { "unifiedroleassignmentscheduleinstance-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue},
                { "unifiedroleassignmentschedulerequest-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue},
                { "unifiedroleeligibilityschedule-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue},
                { "unifiedroleeligibilityscheduleinstance-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue},
                { "unifiedroleeligibilityschedulerequest-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue},
                { "user-chat-teamsapps-csharp-V1-executes", MissingDataKnownIssue with { Message = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/509" } },
                { "user-supportedtimezones-iana-csharp-V1-executes", SDKFunctionParameterKnownIssue },
                { "userconsentrequest-filterbycurrentuser-csharp-V1-executes", MissingDataKnownIssue },
                { "workbookrange-columnsafter-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-columnsbefore-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsabove-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsabove-nocount-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsbelow-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsbelow-nocount-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-visibleview-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrangeview-range-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "appconsentrequest-filterbycurrentuser-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-connectors-3-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-educationuser-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-educationuser-1-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "get-educationuser-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-mailboxsettings-1-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-mailboxsettings-2-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-mailboxsettings-2-csharp-V1-executes", MetadataMissingNavigationPropertyKnownIssue },
                { "get-mailboxsettings-3-csharp-V1-executes", MetadataMissingNavigationPropertyKnownIssue },
                { "get-mailboxsettings-4-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-printjob-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-printjob-csharp-V1-executes", MissingDataKnownIssue with { Message = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/502" } },
                { "get-printjob-withdocumentdata-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-printjob-withdocumentdata-csharp-V1-executes", MissingDataKnownIssue with { Message = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/502" } },
                { "get-printjob-withtasks-csharp-V1-executes", MissingDataKnownIssue with { Message = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/502" } },
                { "list-printconnector-2-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "list-printershare-2-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "user-get-room-lists-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "user-get-rooms-in-tenant-csharp-Beta-executes", NeedsAnalysisKnownIssue },
                { "userconsentrequest-filterbycurrentuser-csharp-Beta-executes", MissingDataKnownIssue },

                { "get-applicationsignindetailedsummary-csharp-Beta-executes", MissingDataKnownIssue },

                { "enum-lists-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "enum-lists-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-applicationtemplate-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-applicationtemplate-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-applicationtemplates-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-applicationtemplates-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-calendar-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-calendar-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-calendarpermission-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-calendarpermission-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-chartpoint-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-chartpoint-csharp-V1-executes", PermissionsExcelIdKnownIssue },
                { "get-chartpointscollection-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-chartpointscollection-csharp-V1-executes", PermissionsExcelIdKnownIssue },
                { "get-chartseries-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-chartseries-csharp-V1-executes", PermissionsExcelIdKnownIssue },
                { "get-deleteditems-count-csharp-Beta-executes", MissingPermissionScopeKnownIssue},
                { "get-deleteditems-count-csharp-V1-executes", MissingPermissionScopeKnownIssue},
                { "get-endpoints-2-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-jobs-3-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-messagerules-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-messagerules-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-organizationalbranding-frlocale-bannerlogo-csharp-V1-executes", MissingPermissionScopeKnownIssue},
                { "get-organizationalbrandingproperties-2-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-organizationalbrandingproperties-2-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-points-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-points-csharp-V1-executes", PermissionsExcelIdKnownIssue },
                { "get-printservice-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-printservice-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-printserviceendpoint-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-printserviceendpoint-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-profilecardproperties-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-regionalandlanguagesettings-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-services-2-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-subscriptions-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-subscriptions-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-swapshiftschangerequest-1-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-swapshiftschangerequest-1-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-user-presences-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-user-presences-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-live-event-recording-csharp-Beta-executes", MissingDataKnownIssue},
                { "get-organizationsettings-csharp-Beta-executes", MissingPermissionScopeKnownIssue},
                { "get-samlorwsfedexternaldomainfederation-csharp-Beta-executes", MissingPermissionScopeKnownIssue},
                { "list-samlorwsfedexternaldomainfederation-csharp-Beta-executes", MissingPermissionScopeKnownIssue},
                { "item-search-all-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "item-search-all-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "list-activities-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-conversation-members-1-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "list-conversation-members-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-identityapiconnectors-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-identityapiconnectors-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "list-printservice-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "list-printserviceendpoint-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "user-get-calendarview-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "user-get-calendarview-csharp-V1-executes", MissingPermissionScopeKnownIssue },
                { "user-reminderview-csharp-Beta-executes", MissingPermissionScopeKnownIssue },
                { "user-reminderview-csharp-V1-executes", MissingPermissionScopeKnownIssue },

                { "get-enabled-dynamic-groups-csharp-V1-executes", SDKMissingCountSupportKnownIssue },

                { "chat-getallmessages-1-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "get-educationmediaresource-from-educationassignment-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "get-educationpowerpointresource-from-educationassignment-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "get-attendee-report-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "get-educationlinkresource-from-educationassignment-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "get-educationfileresource-from-educationassignment-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "channel-getallchannelmessages-1-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "get-educationexcelresource-from-educationassignment-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "get-datapolicyoperation-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "list-authorednote-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "get-devices-by-extensionattribute-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "list-subjectrightsrequest-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "subjectrightsrequest-getfinalattachment-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "get-subjectrightsrequest-csharp-V1-executes", NeedsAnalysisKnownIssue },
                { "subjectrightsrequest-getfinalreport-csharp-V1-executes", NeedsAnalysisKnownIssue },
            };
        }
    }
}
