global using System;
global using System.IO;
global using System.Threading.Tasks;
global using MsGraphSDKSnippetsCompiler;
global using MsGraphSDKSnippetsCompiler.Models;
global using System.Globalization;
global using System.Text;
global using NUnit.Framework;
global using System.Linq;
global using System.Text.RegularExpressions;
global using System.Threading;
global using System.Collections.Generic;
global using static TestsCommon.KnownIssues;
