namespace TestsCommon;

internal static class JavaKnownIssues
{
    /// <summary>
    /// Gets known issues
    /// </summary>
    /// <param name="versionEnum">version to get the known issues for</param>
    /// <returns>A mapping of test names into known Java issues</returns>
    internal static Dictionary<string, KnownIssue> GetJavaCompilationKnownIssues(Versions versionEnum)
    {
        var version = versionEnum == Versions.V1 ? "V1" : "Beta";
        return new Dictionary<string, KnownIssue>()
            {
                {$"unfollow-site-java-{version}-compiles", new KnownIssue(Category.SDK, "SDK doesn't convert actions defined on collections to methods. https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/250") },
                {$"follow-site-java-{version}-compiles", new KnownIssue(Category.SDK, "SDK doesn't convert actions defined on collections to methods. https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/250") },
                {$"update-page-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "See issue: https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/428") },
                {$"get-rooms-in-roomlist-java-{version}-compiles", new KnownIssue(Category.SDK, "SDK doesn't generate type segment in OData URL. https://microsoftgraph.visualstudio.com/Graph%20Developer%20Experiences/_workitems/edit/4997") },

                {$"get-securescore-java-Beta-compiles", new KnownIssue(Category.SDK, "Path had wrong casing in SDK due to an error in the metadata") },
                {$"get-securescorecontrolprofile-java-Beta-compiles", new KnownIssue(Category.SDK, "Path had wrong casing in SDK due to an error in the metadata") },
                {$"get-securescorecontrolprofiles-java-Beta-compiles", new KnownIssue(Category.SDK, "Path had wrong casing in SDK due to an error in the metadata") },
                {$"get-securescores-java-Beta-compiles", new KnownIssue(Category.SDK, "Path had wrong casing in SDK due to an error in the metadata") },
                { "update-alert-java-V1-compiles", new KnownIssue(Category.SDK, "Path had wrong casing in SDK due to an error in the metadata") },

                {$"get-group-transitivemembers-count-java-{version}-compiles", new KnownIssue(Category.SDK, "Missing method in SDK generation https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/318") },
                {$"get-user-memberof-count-only-java-{version}-compiles", new KnownIssue(Category.SDK, "Missing method in SDK generation https://github.com/microsoftgraph/MSGraph-SDK-Code-Generator/issues/318") },

                {$"get-deleteditems-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "Missing support for odata cast https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/361") },
                {$"get-all-roomlists-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "Missing support for odata cast https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/361") },
                {$"get-all-rooms-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "Missing support for odata cast https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/361") },
                {$"get-pr-count-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "Missing support for odata cast https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/361") },
                {$"get-tier-count-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "Missing support for odata cast https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/361") },
                {$"get-count-group-only-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "Missing support for odata cast https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/361") },
                {$"get-count-only-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "Missing support for odata cast https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/361") },
                {$"get-count-user-only-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "Missing support for odata cast https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/361") },

                { "update-accesspackageassignmentpolicy-java-Beta-compiles", new KnownIssue(Category.SDK, "Missing property") },

                {$"create-list-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "Duplicated variable name") },

                {$"create-listitem-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "Should be in additional data manager") },
                {$"update-listitem-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "Should be in additional data manager") },
                {$"update-plannerassignedtotaskboardtaskformat-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "Should be in additional data manager") },
                {$"update-plannerplandetails-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "Should be in additional data manager") },

                {$"create-or-get-onlinemeeting-java-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Conflicting Graph and Java type") },

                {$"get-one-thumbnail-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "Issue with Size argument") },
                {$"get-thumbnail-content-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "Issue with Size argument") },

                {$"user-supportedtimezones-iana-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "Missing quotes around query string parameter argument?") },

                { "alert-updatealerts-java-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Enums are not generated properly") },

                {$"get-channel-messages-delta-2-java-{version}-compiles", new KnownIssue(Category.Metadata, "Delta function is not declared") },
                {$"get-channel-messages-delta-3-java-{version}-compiles", new KnownIssue(Category.Metadata, "Delta function is not declared") },

                {$"upload-via-put-id-java-{version}-compiles", new KnownIssue(Category.SnippetGeneration, "Missing support for content: https://github.com/microsoftgraph/microsoft-graph-devx-api/issues/371") },

                { "create-printer-java-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Parameters with null values are not accounted for as action parameters") },

                { "get-group-java-Beta-compiles", new KnownIssue(Category.TestGeneration, "Imports need to be deduplicated for namespaces") },
                { "get-set-java-Beta-compiles", new KnownIssue(Category.TestGeneration, "Imports need to be deduplicated for namespaces") },
                { "update-set-java-Beta-compiles", new KnownIssue(Category.TestGeneration, "Imports need to be deduplicated for namespaces") },
                { "update-term-java-Beta-compiles", new KnownIssue(Category.TestGeneration, "Imports need to be deduplicated for namespaces") },
                { "get-store-java-Beta-compiles", new KnownIssue(Category.TestGeneration, "Imports need to be deduplicated for namespaces") },
                { "update-store-java-Beta-compiles", new KnownIssue(Category.TestGeneration, "Imports need to be deduplicated for namespaces") },
                { "get-term-java-Beta-compiles", new KnownIssue(Category.TestGeneration, "Imports need to be deduplicated for namespaces") },
                { "get-relation-java-Beta-compiles", new KnownIssue(Category.TestGeneration, "Imports need to be deduplicated for namespaces") },
                { "create-term-from--java-Beta-compiles", new KnownIssue(Category.TestGeneration, "Imports need to be deduplicated for namespaces") },

                { "update-educationpointsoutcome-java-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Lossy conversion") },
                { "educationsubmission-return-java-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Reserved keyword usage") },
                { "tablecolumncollection-add-java-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Tries to instantiate a primite??") },
                { "group-evaluatedynamicmembership-java-Beta-compiles", new KnownIssue(Category.SnippetGeneration, "Double Quotes not escaped") },
                { "create-educationrubric-from-educationuser-java-Beta-compiles", new KnownIssue(Category.TestGeneration, "Code truncated???") },

                { "securescorecontrolprofiles-update-java-V1-compiles", new KnownIssue(Category.HTTP, HttpSnippetWrong + ": A list of SecureScoreControlStateUpdate objects should be provided instead of placeholder string.") },

                { "remove-rejectedsender-from-group-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "delete-acceptedsenders-from-group-java-V1-compiles", NeedsAnalysisKnownIssue },
                { $"call-transfer-java-{version}-compiles", NeedsAnalysisKnownIssue },
                { "accesspackageassignment-filterbycurrentuser-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "accesspackageassignmentrequest-filterbycurrentuser-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "accessreviewinstance-filterbycurrentuser-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "accessreviewinstancedecisionitem-filterbycurrentuser-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "accessreviewscheduledefinition-filterbycurrentuser-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "add-incompatibleaccesspackage-to-accesspackage-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "appconsentrequest-filterbycurrentuser-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "application-addkey-1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "authenticationmethodsroot-usersregisteredbyfeature-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "authenticationmethodsroot-usersregisteredbymethod-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "caseexportoperation-getdownloadurl-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "contact-delta-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "contactfolder-delta-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "convert-item-content-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-accesspackageassignmentpolicy-from-accesspackageassignmentpolicies-questions-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-accesspackageassignmentrequest-from-accesspackageassignmentrequests-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-accesspackageresourcerequest-from-accesspackageresourcerequests-with-accesspackageresourceenvironment-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-accesspackageresourcerequest-from-accesspackageresourcerequests-with-accesspackageresourceenvironment-new-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-accesspackageresourcerequest-from-accesspackageresourcerequests4-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-accesspackageresourcerequest-from-accesspackageresourcerequests5-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-application-from-connectorgroup-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-b2cuserflow-from-b2cuserflows-apiconnectors-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-b2cuserflow-from-b2cuserflows-identityprovider-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-b2cuserflow-from-b2cuserflows-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-b2xuserflow-from-b2xuserflows-apiconnectors-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-b2xuserflow-from-b2xuserflows-identityproviders-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-b2xuserflow-from-b2xuserflows-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-conditionalaccesspolicy-from-conditionalaccessroot-3-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-connection-from-external-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-connectorgroup-from-connector-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-custodian-from--java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-datasource-from--1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-datasource-from--2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-deployment-from--java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-directorysetting-from-settings-for-guests-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-educationassignment-from-educationclass-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-educationrubric-from-educationuser-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-externalgroup-from-connection-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-externalgroupmember-from--1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-externalgroupmember-from--2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-externalgroupmember-from--3-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-identityuserflow-from-identitycontainer-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-legalhold-from--java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-noncustodialdatasource-from--java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-schema-from-connection-async-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-sitesource-from--1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-sitesource-from--2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-sourcecollection-from--java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-tag-from--java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-tenanttag-from--java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-unifiedgroupsource-from--java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-unifiedroleassignmentschedulerequest-from-unifiedroleassignmentschedulerequests-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-unifiedroleassignmentschedulerequest-from-unifiedroleassignmentschedulerequests-selfactivate-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-unifiedroleeligibilityschedulerequest-from-unifiedroleeligibilityschedulerequests-adminremove-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-unifiedroleeligibilityschedulerequest-from-unifiedroleeligibilityschedulerequests-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-updatableassetgroup-from--java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-usersource-from--1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-usersource-from--2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "delete-userflowlanguagepage-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "deploymentaudience-updateaudience-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "deploymentaudience-updateaudiencebyid-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "directoryobject-delta-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "download-item-content-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "ediscoverycase-close-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-attendeereport-app-token-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-azureaddevice-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-b2cuserflows-apiconnectorconfiguration-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-b2xuserflows-apiconnectorconfiguration-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-callrecord-expanded-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-callrecord-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-callrecord-sessions-expanded-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-callrecord-sessions-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-case-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-cloudpcconnection-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-cloudpcdevice-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-cloudpcoverview-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-conditionalaccesspolicycoverage-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-connection-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-connectionoperation-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-connections-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-credentialuserregistrationssummary-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-custodian-1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-custodian-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-deployment-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-devicecompliancepolicysettingstatesummary-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-group-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-group-3-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-group-transitivemembers-odatacast-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-legalhold-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-mailboxsettings-1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-mailboxsettings-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-mailboxsettings-4-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-manageddevicecompliance-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-manageddevicecompliancetrend-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-managementaction-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-managementactiontenantdeploymentstatus-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-managementintent-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-managementtemplate-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-noncustodialdatasource-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-organizationalbrandingproperties-10-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-organizationalbrandingproperties-5-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-organizationalbrandingproperties-6-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-printsettings-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-recording-app-token-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-resource-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-responsibilities-from-profile-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-reviewset-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-reviewsetquery-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-riskyuser-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-schema-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-set-1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-set-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-settings-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-settings-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-sitecollection-termstore-set-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-sitesource-1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-sitesource-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-sourcecollection-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-tag-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-tenant-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-tenantcustomizedinformation-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-tenantdetailedinformation-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-tenantgroup-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-tenanttag-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-term-1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-term-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-timeoffrequest-1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-transitivereports-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-transitivereports-user-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-unifiedgroupsource-1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-unifiedgroupsource-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-unifiedroleassignmentschedulerequest-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-unifiedroleeligibilityschedulerequest-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-updatableasset-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-updatableassetgroup-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-usersource-1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-usersource-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-version-contents-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-windowsdevicemalwarestate-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-windowsprotectionstate-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "governanceroleassignmentrequest-post-1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "governanceroleassignmentrequest-post-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "governanceroleassignmentrequest-post-3-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "governanceroleassignmentrequest-post-4-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "governanceroleassignmentrequest-post-5-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "governanceroleassignmentrequest-post-6-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "group-evaluatedynamicmembership-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-addtoreviewsetoperation-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-aggregatedpolicycompliance-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-azureaddevice-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-case-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-caseoperation-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-catalogentry-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-cloudpcconnection-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-cloudpcdevice-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-cloudpcoverview-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-conditionalaccesspolicycoverage-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-credentialuserregistrationssummary-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-datasource-1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-datasource-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-datasource-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-deployment-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-devicecompliancepolicysettingstatesummary-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-estimatestatisticsoperation-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-legalhold-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-manageddevicecompliance-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-managementaction-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-managementactiontenantdeploymentstatus-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-managementintent-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-managementtemplate-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-noncustodialdatasource-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-reviewset-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-reviewsetquery-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-riskyuser-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-sitesource-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-sourcecollection-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-tag-1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-tag-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-tenant-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-tenantcustomizedinformation-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-tenantdetailedinformation-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-tenantgroup-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-tenanttag-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-updatableasset-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-updatableassetgroup-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-usersource-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-windowsdevicemalwarestate-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-windowsprotectionstate-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "mailfolder-delta-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "managementaction-apply-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "managementactiontenantdeploymentstatus-changedeploymentstatus-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "message-delta-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "post-case-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "post-channelmessage-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "post-channelmessage-3-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "post-chatmessage-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "post-reviewset-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "post-reviewsetquery-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "put-b2cuserflows-apiconnectorconfiguration-disable-postattributecollection-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "put-b2cuserflows-apiconnectorconfiguration-postattributecollection-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "put-b2cuserflows-apiconnectorconfiguration-postfederationsignup-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "put-b2xuserflows-apiconnectorconfiguration-disable-postattributecollection-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "put-b2xuserflows-apiconnectorconfiguration-postattributecollection-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "put-b2xuserflows-apiconnectorconfiguration-postfederationsignup-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "reportroot-getm365appplatformusercounts-csv-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "reportroot-getm365appplatformusercounts-json-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "reportroot-getm365appusercoundetail-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "reportroot-getm365appusercountdetail-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "reportroot-getm365appusercounts-csv-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "reportroot-getm365appusercounts-json-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "reports-getgrouparchivedprintjobs-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "reports-getprinterarchivedprintjobs-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "reports-getuserarchivedprintjobs-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "reviewset-addtoreviewset-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "reviewset-export-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "reviewsetquery-applytags-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "tag-ashierarchy-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "team-put-schedule-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "tenantgroup-tenantsearch-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "tenanttag-assigntag-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "tenanttag-unassigntag-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "unifiedroleassignmentschedule-filterbycurrentuser-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "unifiedroleassignmentscheduleinstance-filterbycurrentuser-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "unifiedroleassignmentschedulerequest-filterbycurrentuser-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "unifiedroleeligibilityschedule-filterbycurrentuser-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "unifiedroleeligibilityscheduleinstance-filterbycurrentuser-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "unifiedroleeligibilityschedulerequest-filterbycurrentuser-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "updatableasset-enrollassets-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "updatableasset-enrollassetsbyid-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "updatableasset-unenrollassets-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "updatableasset-unenrollassetsbyid-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "updatableassetgroup-addmembers-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "updatableassetgroup-addmembersbyid-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "updatableassetgroup-removemembers-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "updatableassetgroup-removemembersbyid-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-case-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-connection-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-custodian-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-deployment-1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-deployment-2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-externalitem-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-legalhold-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-organizationalbrandingproperties-5-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-reviewsetquery-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-sourcecollection-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-tag-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-temporaryaccesspassauthenticationmethodconfiguration-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-tenantcustomizedinformation-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-tenanttag-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "userconsentrequest-filterbycurrentuser-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "accessreviewinstance-filterbycurrentuser-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "accessreviewinstancedecisionitem-filterbycurrentuser-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "accessreviewscheduledefinition-filterbycurrentuser-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "add-educationcategory-to-educationassignment-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "appconsentrequest-filterbycurrentuser-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "application-addkey-1-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "convert-item-content-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "create-b2xuserflow-from-b2xuserflows-apiconnectors-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "create-b2xuserflow-from-b2xuserflows-identityproviders-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "create-b2xuserflow-from-b2xuserflows-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "create-conditionalaccesspolicy-from-conditionalaccessroot-3-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "create-educationassignment-from-educationclass-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "create-educationrubric-from-educationassignment-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "create-educationrubric-from-educationuser-2-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "create-externalconnection-from-connections-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "create-schema-from-connection-async-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "delete-educationrubric-from-educationassignment-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "delete-userflowlanguagepage-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "download-item-content-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "educationsubmission-return-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-b2xuserflows-apiconnectorconfiguration-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-callrecord-expanded-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-callrecord-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-callrecord-sessions-expanded-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-callrecord-sessions-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-connectionoperation-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-externalconnection-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-group-transitivemembers-odatacast-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-mailboxsettings-2-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-mailboxsettings-3-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-organizationalbrandingproperties-10-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-organizationalbrandingproperties-5-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-organizationalbrandingproperties-6-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-printsettings-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-resource-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-schema-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-timeoffrequest-1-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-version-contents-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "list-administrativeunit-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "list-externalconnection-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "mailfolder-delta-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "post-channelmessage-2-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "post-channelmessage-3-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "post-chatmessage-2-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "printer-create-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "put-b2xuserflows-apiconnectorconfiguration-disable-postattributecollection-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "put-b2xuserflows-apiconnectorconfiguration-postattributecollection-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "put-b2xuserflows-apiconnectorconfiguration-postfederationsignup-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "serviceprincipal-addkey-1-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "update-educationpointsoutcome-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "update-externalconnection-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "update-externalitem-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "update-organizationalbrandingproperties-5-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "userconsentrequest-filterbycurrentuser-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "update-b2cuserflows-userflowidentityproviders-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-b2xuserflows-userflowidentityprovider-java-Beta-compiles ", NeedsAnalysisKnownIssue },
                { "callrecord-getdirectroutingcalls-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "callrecord-getpstncalls-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "create-aad-group-identity-from-group-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "create-aad-user-identity-from-group-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "create-external-group-identity-from-group-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "create-externalgroup-from-connection-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "create-term-from--java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-externalgroup-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-group-2-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-group-3-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-group-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-relation-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-set-2-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-store-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-term-1-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-term-2-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "update-externalgroup-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "update-set-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "update-store-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "update-term-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "create-claimsmappingpolicy-from-claimsmappingpolicies-java-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-deleteditems-count-java-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-organizationalbranding-frlocale-bannerlogo-java-V1-compiles", NeedsAnalysisKnownIssue},
                { "get-organizationalbrandinglocalization-locale-signinpagetext-java-V1-compiles", NeedsAnalysisKnownIssue},
                { "update-organizationalbrandinglocalization-java-V1-compiles", NeedsAnalysisKnownIssue},
                { "callrecord-getdirectroutingcalls-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "callrecord-getpstncalls-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "create-claimsmappingpolicy-from-claimsmappingpolicies-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "create-externaldomainname-from--java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "create-noncustodialdatasource-from-email-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "create-noncustodialdatasource-from-siteurl-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "create-unifiedgroupsource-from-email-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "create-unifiedgroupsource-from-id-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "get-attendee-report-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "get-deleteditems-count-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "get-live-event-recording-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "get-organizationalbranding-frlocale-bannerlogo-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "get-organizationalbrandinglocalization-locale-signinpagetext-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "get-samlorwsfedexternaldomainfederation-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "get-simulationreportoverview-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "list-externaldomainname-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "list-samlorwsfedexternaldomainfederation-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "list-usersimulationdetails-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "participant-startholdmusic-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "update-b2xuserflows-userflowidentityprovider-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "update-organizationalbrandinglocalization-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "update-samlorwsfedexternaldomainfederation-java-Beta-compiles", NeedsAnalysisKnownIssue},
                { "accesspackage-filterbycurrentuser-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "accesspackageassignment-filterbycurrentuser-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "accesspackageassignmentrequest-filterbycurrentuser-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "create-accesspackageassignmentrequest-from-accesspackageassignmentrequests-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "create-authorednote-from--java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-accesspackageassignmentrequest-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-attendee-report-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "get-rows-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "participant-startholdmusic-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "range-cell-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "range-clear-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "range-column-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "range-delete-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "range-entirecolumn-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "range-entirerow-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "range-insert-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "range-lastcell-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "range-lastcolumn-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "range-lastrow-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "range-merge-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "range-unmerge-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "range-usedrange-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "range-usedrange-valuesonly-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "workbookrange-columnsafter-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "workbookrange-columnsbefore-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "workbookrange-rowsabove-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "workbookrange-rowsabove-nocount-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "workbookrange-rowsbelow-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "workbookrange-rowsbelow-nocount-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "workbookrange-visibleview-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "workbookrangeview-range-java-V1-compiles", NeedsAnalysisKnownIssue },
                { "basetask-delta-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "basetasklist-delta-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "cloudpconpremisesconnection-runhealthcheck-1-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-accesspackageassignmentrequest-from-accesspackageassignmentrequests-5-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-accesspackageassignmentrequest-from-accesspackageassignmentrequests-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-accesspackageresourcerequest-from-accesspackageresourcerequests-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "create-authorednote-from--java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "delete-basetask-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "delete-checklistitem-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "delete-linkedresource-v2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-accesspackageassignmentrequest-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-basetask-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-basetasklist-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-checklistitem-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-linkedresource-v2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "get-rows-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-basetask-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-basetasklist-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-checklistitem-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-linkedresource-v2-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "list-registratrants-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "post-privilegedroleassignmentrequest-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "range-clear-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "range-delete-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "range-entirecolumn-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "range-entirerow-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "range-insert-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "range-lastcell-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "range-lastcolumn-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "range-lastrow-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "range-merge-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "range-unmerge-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "range-usedrange-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "search-query-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "update-schema-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "workbookrange-columnsafter-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "workbookrange-columnsbefore-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "workbookrange-rowsabove-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "workbookrange-rowsbelow-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "workbookrange-visibleview-java-Beta-compiles", NeedsAnalysisKnownIssue },
                { "workbookrangeview-range-java-Beta-compiles", NeedsAnalysisKnownIssue },
            };
    }
}
