namespace TestsCommon;

public static class PowerShellKnownIssues
{
    public static Dictionary<string, KnownIssue> GetPowerShellExecutionKnownIssues(Versions versionEnum)
    {
        var version = versionEnum.ToString();
        return new Dictionary<string, KnownIssue>
        {
                { "list-printusagebyuser-1-powershell-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "list-printusagebyprinter-2-powershell-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "list-printusagebyprinter-1-powershell-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "list-printusagebyuser-2-powershell-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "get-chartgridlines-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-assignments-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-cloudpcgalleryimage-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-teams-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-customsecurityattributedefinition-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-attributeset-single-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-customsecurityattributedefinition-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-attendancerecord-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-endpoints-4-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-insightssettingspeoplerequest-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-organizationalbranding-locale-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-endpoints-5-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-endpoints-6-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-attributeset-all-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-attributeset-top-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-allowedvalue-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-attendancereports-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-customsecurityattributedefinition-filter-attributeset-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-authenticationcontextclassreference-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-cloudpcgalleryimage-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-customsecurityattributedefinition-filter-name-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-allowedvalue-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-resource-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-chartgridlines-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-permission-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-attributeset-orderby-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-endpoints-3-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-basetasklist-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "accesspackageassignment-filterbycurrentuser-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "accesspackageassignmentrequest-filterbycurrentuser-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "accessreviewinstance-filterbycurrentuser-powershell-Beta-executes", SDKFunctionParameterKnownIssue },
                { "accessreviewinstancedecisionitem-filterbycurrentuser-powershell-Beta-executes", SDKFunctionParameterKnownIssue },
                { "accessreviewscheduledefinition-filterbycurrentuser-powershell-Beta-executes", SDKFunctionParameterKnownIssue },
                { "authenticationmethodsroot-usersregisteredbyfeature-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "authenticationmethodsroot-usersregisteredbymethod-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "bookingbusiness-getcalendarview-powershell-Beta-executes", MissingDataKnownIssue },
                { "cloudpcauditevent-getauditactivitytypes-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "cloudpcdeviceimage-getsourceimages-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "connector-get-memberof-powershell-Beta-executes", MissingDataKnownIssue },
                { "contenttype-ispublished-powershell-Beta-executes", MissingDataKnownIssue },
                { "convert-item-content-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "drive-root-subscriptions-socketio-powershell-Beta-executes", MissingDataKnownIssue },
                { "event-delta-calendarview-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "event-get-attachments-beta-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-a-count-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-a-count-endswith-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-accesspackageassignmentpolicy-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageassignmentrequest-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageassignmentresourcerole-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageresourceenvironment-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageresourceroles-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackageresourceroles2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-accesspackagesincompatiblewith-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-accessreviewhistorydefinition-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-agentgroups-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-agents-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-alert-powershell-Beta-executes", EphemeralAlertDataKnownIssue },
                { "get-all-roomlists-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-all-rooms-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-allchannelmessages-1-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-allowedgroups-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-allowedusers-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-and-expand-item-attachment-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-appconsentrequest-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-applications-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-appmanagementpolicy-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-appointments-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-approval-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-approvalstep-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-approvalstep-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-attendeereport-app-token-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-audioroutinggroup-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-audioroutinggroups-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-authenticationmethod-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-azureaddevice-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-b2cauthenticationmethodspolicy-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-b2cuserflow-list-identityproviders-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-b2cuserflow-list-userflowidentityproviders-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-b2cuserflows-apiconnectorconfiguration-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-b2cuserflows-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { $"get-b2xuserflows-apiconnectorconfiguration-powershell-{version}-executes", StructuralPropertiesAreNotHandledKnownIssue},
                { "get-bitlockerrecoverykey-1-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-bitlockerrecoverykey-2-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-bitlockerrecoverykey-3-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-bitlockerrecoverykey-4-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-bookingappointment-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-bookingbusiness-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-bookingcurrency-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-bookingcustomer-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-bookingservice-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-bookingstaffmember-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-built-in-cloudpc-role-unifiedroledefinition-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-built-in-entitlementmanagement-role-unifiedroledefinition-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-bundle-and-children-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-bundle-metadata-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-call-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-call-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-callrecord-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-callrecord-expanded-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-callrecord-sessions-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-callrecord-sessions-expanded-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-case-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-chat-operation-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpc-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcauditevent-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcconnection-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcdevice-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcdeviceimage-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpconpremisesconnection-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpconpremisesconnection-withdetails-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcoverview-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcprovisioningpolicy-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcprovisioningpolicy-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcusersetting-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-cloudpcusersetting-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-comments-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-conditionalaccesspolicycoverage-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-connection-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-connectionoperation-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-connections-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-connector-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-connector-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-connectorgroup-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-connectorgroup-members-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-connectorgroups-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-connectors-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-contract-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-continuousaccessevaluationpolicy-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-credentialuserregistrationssummary-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-custodian-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-custodian-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-customers-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-deleteditems-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-deployment-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-directorysetting-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-directorysettingtemplate-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-document-value-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-educationalactivity-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-educationsubmissionresource-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-educationsynchronizationprofile-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-educationsynchronizationprofile-error-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-educationsynchronizationprofile-status-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-educationsynchronizationprofile-uploadurl-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-emailauthenticationmethod-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-emailauthenticationmethodconfiguration-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-enabled-dynamic-groups-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-endpoint-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-event-based-on-eventmessage-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-event-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-event-in-text-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-event-multiple-locations-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-fido2authenticationmethod-1-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-fido2authenticationmethodconfiguration-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-file-attachment-beta-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-governanceresources-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-governancerolesetting-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-group-3-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-identityuserflow-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-identityuserflowattributeassignment-1-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-identityuserflowattributeassignment-3-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-identityuserflowattributeassignment-expand-1-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-identityuserflowattributeassignment-expand-3-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-incompatiblegroups-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-informationprotectionlabel-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-instances-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-item-attachment-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-serviceplans-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-federatedidentitycredential-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-user-assignments-expand-submissions-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-subjectrightsrequest-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-user-assignments-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-supportedregions-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-devices-by-extensionattribute-powershell-Beta-executes", MissingDataKnownIssue with {GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/570"} },
                { "get-custom-question-powershell-Beta-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/573"} },
                { "list-custom-questions-powershell-Beta-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/573"} },
                { "get-registration-powershell-Beta-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/573"} },
                { "get-subjectrightsrequest-powershell-Beta-executes", NeedsAnalysisKnownIssue with{ GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/574" } },
                { "list-authorednote-powershell-Beta-executes", NeedsAnalysisKnownIssue with{ GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/574" } },
                { "list-registratrants-powershell-Beta-executes", NeedsAnalysisKnownIssue with{ GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/573" } },
                { "subjectrightsrequest-getfinalattachment-powershell-Beta-executes", NeedsAnalysisKnownIssue with{ GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/574" } },
                { "subjectrightsrequest-getfinalreport-powershell-Beta-executes", NeedsAnalysisKnownIssue with{ GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/574" } },
                { "get-federatedidentitycredential-powershell-Beta-executes", MissingDataKnownIssue with{ GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/575" } },
                { "get-workbookcommentreply-powershell-Beta-executes", NeedsAnalysisKnownIssue with{ GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/576" } },
                { "get-itemaddress-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-itememail-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-itempatent-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-itemphone-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-itempublication-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-jobs-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-keysets-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-labels-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-languageproficiency-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-legalhold-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-list-multi-expand-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-mailboxsettings-2-powershell-V1-executes", StructuralPropertiesAreNotHandledKnownIssue },
                { "get-mailboxsettings-3-powershell-V1-executes", StructuralPropertiesAreNotHandledKnownIssue },
                { "get-manageddevicecompliance-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-manageddevicecompliancetrend-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-managementaction-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-managementactiontenantdeploymentstatus-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-managementintent-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-managementtemplate-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-manager-1-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-meetingattendancereport-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-messagerule-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-microsoftauthenticatorauthenticationmethod-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-microsoftauthenticatorauthenticationmethodconfiguration-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-mobilitymanagementpolicy-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-noncustodialdatasource-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-onenoteoperation-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-onlinemeeting-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-onpremisesagent-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-onpremisesagentgroup-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-onpremisespublishingprofile-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-opentypeextension-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-opentypeextension-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-opentypeextension-4-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-operation-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-organizationalbrandingproperties-5-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-organizationalbrandingproperties-6-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-outlooktask-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-outlooktask-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-outlooktaskfolder-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-outlooktaskgroup-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-page-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-participant-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-participants-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-passwordauthenticationmethod-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-passwordlessmicrosoftauthenticatorauthenticationmethod-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-passwordlessmicrosoftauthenticatorauthenticationmethodconfiguration-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-personanniversary-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-personannotation-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-personaward-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-personcertification-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-personinterest-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-personname-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-personwebsite-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-phoneauthenticationmethod-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-pivottables-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-plans-1-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-printer-tasktrigger-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-printershare-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-printoperation-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-printsettings-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-printusagebyprinter-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-printusagebyuser-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-privilegedapproval-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-privilegedapproval-2-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedrole-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-privilegedroleassignment-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-privilegedroleassignmentrequest-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedroleassignments-1-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedroleassignments-2-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedroleassignments-3-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedroleassignments-4-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedroles-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-privilegedrolesettings-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-privilegedrolesummary-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-profilecardproperty-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-programcontrol-from-program-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-projectparticipation-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-publishedresource-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-publishedresources-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-recording-app-token-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-reference-attachment-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-relation-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-relyingpartydetailedsummary-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-replies-2-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-resources-2-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-reviewset-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-reviewsetquery-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-riskdetection-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-riskyuser-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-riskyuser-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-riskyuser-historyitem-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-riskyuser-historyitem-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-roledefinitions-cloudpc-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-rows-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-rubric-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-schema-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-securityaction-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-services-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-set-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-set-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-settings-2-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-settings-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-sitesource-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-sitesource-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-skillproficiency-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-smsauthenticationmethodconfiguration-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-sourcecollection-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-staffmembers-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-subscription-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-synchronizationjob-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-synchronizationschema-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-tablerow-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-tag-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-task-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-taskdefinition-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-taskfolders-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-teamworktag-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-teamworktagmember-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-temporaryaccesspassauthenticationmethod-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-tenant-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-tenantcustomizedinformation-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-tenantdetailedinformation-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-tenantgroup-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-tenanttag-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-term-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-tiindicator-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-trustframeworkkeyset-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-trustframeworks-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-unifiedgroupsource-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedgroupsource-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleassignment-3-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleassignmentmultiple-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleassignmentschedule-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleassignmentscheduleinstance-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleassignmentschedulerequest-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleeligibilityschedule-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleeligibilityscheduleinstance-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedroleeligibilityschedulerequest-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedrolemanagementpolicy-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedrolemanagementpolicyassignment-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-unifiedrolemanagementpolicyrule-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-updatableasset-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-updatableassetgroup-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-useraccountinformation-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-userconsentrequest-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-userflowlanguageconfiguration-1-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-userflowlanguageconfiguration-3-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-userflowlanguageconfiguration-filter-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-userflowlanguagepage-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-userflowlanguagepage-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-userflowlanguagepage-3-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-userflows-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-userriskhitsory-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-userriskhitsory-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-usersource-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-usersource-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-webaccount-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-windowsdevicemalwarestate-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-windowshelloforbusinessauthenticationmethod-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-windowsprotectionstate-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-workbookcomment-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-workbookoperation-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-workbookpivottable-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-workposition-powershell-Beta-executes", MissingDataKnownIssue },
                { "identityuserflowattributeassignment-getorder-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-addtoreviewsetoperation-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-aggregatedpolicycompliance-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-album-bundles-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-all-bundles-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-appmanagementpolicyappliesto-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-appmanagementpolicyappliesto-select-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-b2cuserflows-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-b2cuserflows-expand-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-caseoperation-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-cloudpcauditevent-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-cloudpcconnection-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-cloudpcdevice-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-cloudpcdeviceimages-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-cloudpconpremisesconnections-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-cloudpcoverview-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-cloudpcprovisioningpolicies-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-cloudpcs-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-cloudpcunifiedroleassignmentmultiple-1-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-cloudpcunifiedroleassignmentmultiple-2-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-cloudpcusersetting-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-conditionalaccesspolicycoverage-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-credentialuserregistrationssummary-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-datasource-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-datasource-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-datasource-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-estimatestatisticsoperation-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-group-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-legalhold-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-manageddevicecompliance-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-managementaction-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-managementactiontenantdeploymentstatus-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-managementintent-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-managementtemplate-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-noncustodialdatasource-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-reviewset-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-reviewsetquery-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-riskdetection-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-riskyuser-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-sitesource-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-sourcecollection-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-tag-1-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-tag-2-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-teamworktagmember-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-tenant-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-tenantcustomizedinformation-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-tenantdetailedinformation-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-tenantgroup-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-tenanttag-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-unifiedrolemanagementpolicy-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-unifiedrolemanagementpolicyassignment-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-unifiedrolemanagementpolicyrule-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-updatableasset-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "list-userconsentrequest-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-usersource-powershell-Beta-executes", MissingDataKnownIssue },
                { "list-windowsdevicemalwarestate-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-windowsprotectionstate-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "outlook-task-get-attachments-powershell-Beta-executes", MissingDataKnownIssue },
                { "outlooktaskfolder-get-tasks-powershell-Beta-executes", MissingDataKnownIssue },
                { "privilegedapproval-myrequests-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "privilegedroleassignment-my-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "privilegedroleassignmentrequest-my-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "rbacapplication-rolescheduleinstances-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "rbacapplication-roleschedules-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "search-sites-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "servicehealthissue-incidentreport-powershell-Beta-executes", MissingDataKnownIssue },
                { "synchronizationschema-filteroperators-powershell-Beta-executes", MissingDataKnownIssue },
                { "synchronizationschema-functions-powershell-Beta-executes", MissingDataKnownIssue },
                { "tablerow-range-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "tag-ashierarchy-powershell-Beta-executes", MissingDataKnownIssue },
                { "teamsappicon-get-hostedcontent-coloricon-value-powershell-Beta-executes", MissingDataKnownIssue },
                { "teamsappicon-get-hostedcontentbytes-outlineicon-value-powershell-Beta-executes", MissingDataKnownIssue },
                { "timecard-get-powershell-Beta-executes", MissingDataKnownIssue },
                { "trustframeworkkeyset-getactivekey-powershell-Beta-executes", MissingDataKnownIssue },
                { "user-chat-teamsapps-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "user-get-rooms-from-specific-list-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "user-supportedtimezones-iana-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "virtualendpoint-geteffectivepermissions-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "workbookrange-columnsafter-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-columnsbefore-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsabove-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsbelow-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-visibleview-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "workbookrangeview-range-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "callrecord-getdirectroutingcalls-powershell-Beta-executes", MissingDataKnownIssue},
                { "callrecord-getpstncalls-powershell-Beta-executes", MissingDataKnownIssue},
                { "get-attendance-report-powershell-Beta-executes", MissingDataKnownIssue},
                { "get-attendee-report-powershell-Beta-executes", MissingDataKnownIssue},
                { "get-organizationalbranding-frlocale-bannerlogo-powershell-Beta-executes", MissingDataKnownIssue},
                { "get-simulationreportoverview-powershell-Beta-executes", MissingDataKnownIssue},
                { "get-softwareoathauthenticationmethod-powershell-Beta-executes", MissingDataKnownIssue},
                { "list-externaldomainname-powershell-Beta-executes", MissingDataKnownIssue},
                { "list-usersimulationdetails-powershell-Beta-executes", MissingDataKnownIssue},
                { "manageddevice-getcloudpcremoteactionresults-powershell-Beta-executes", MissingDataKnownIssue},
                { "unifiedroleassignmentschedule-filterbycurrentuser-powershell-Beta-executes", NeedsAnalysisKnownIssue},
                { "unifiedroleassignmentscheduleinstance-filterbycurrentuser-powershell-Beta-executes", NeedsAnalysisKnownIssue},
                { "unifiedroleassignmentschedulerequest-filterbycurrentuser-powershell-Beta-executes", NeedsAnalysisKnownIssue},
                { "unifiedroleeligibilityschedule-filterbycurrentuser-powershell-Beta-executes", NeedsAnalysisKnownIssue},
                { "unifiedroleeligibilityscheduleinstance-filterbycurrentuser-powershell-Beta-executes", NeedsAnalysisKnownIssue},
                { "unifiedroleeligibilityschedulerequest-filterbycurrentuser-powershell-Beta-executes", NeedsAnalysisKnownIssue},
                { "appconsentrequest-filterbycurrentuser-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-connectors-3-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-educationuser-1-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-educationuser-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-mailboxsettings-1-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-mailboxsettings-2-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-mailboxsettings-4-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-printjob-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "get-printjob-withdocumentdata-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "user-get-room-lists-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "user-get-rooms-in-tenant-powershell-Beta-executes", NeedsAnalysisKnownIssue },
                { "userconsentrequest-filterbycurrentuser-powershell-Beta-executes", MissingDataKnownIssue },
                { "get-applicationsignindetailedsummary-powershell-Beta-executes", MissingDataKnownIssue },
                { "enum-lists-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-applicationtemplate-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-applicationtemplates-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-calendar-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-calendarpermission-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-chartpoint-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-chartpointscollection-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-chartseries-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-deleteditems-count-powershell-Beta-executes", MissingPermissionScopeKnownIssue},
                { "get-endpoints-2-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-jobs-3-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-messagerules-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-organizationalbrandingproperties-2-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-points-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-printservice-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-printserviceendpoint-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-profilecardproperties-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-regionalandlanguagesettings-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-services-2-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-subscriptions-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-swapshiftschangerequest-1-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-user-presences-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-live-event-recording-powershell-Beta-executes", MissingDataKnownIssue},
                { "get-organizationsettings-powershell-Beta-executes", MissingPermissionScopeKnownIssue},
                { "get-samlorwsfedexternaldomainfederation-powershell-Beta-executes", MissingPermissionScopeKnownIssue},
                { "list-samlorwsfedexternaldomainfederation-powershell-Beta-executes", MissingPermissionScopeKnownIssue},
                { "item-search-all-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-activities-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-conversation-members-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "list-identityapiconnectors-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "user-get-calendarview-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "user-reminderview-powershell-Beta-executes", MissingPermissionScopeKnownIssue },
                { "get-plans-1-powershell-V1-executes", HTTPKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/microsoft-graph-docs/issues/14686" }},
                { "get-bitlockerrecoverykey-powershell-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/607" } },
                { "get-bitlockerrecoverykey-key-powershell-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/607" } },
                { "accessreviewinstance-filterbycurrentuser-powershell-V1-executes", SDKFunctionParameterKnownIssue },
                { "accessreviewinstancedecisionitem-filterbycurrentuser-powershell-V1-executes", SDKFunctionParameterKnownIssue },
                { "event-get-attachments-v1-powershell-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/610" } },
                { "get-event-powershell-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/610" } },
                { "get-event-multiple-locations-powershell-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/610" } },
                { "get-instances-powershell-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/610" } },
                { "get-alert-powershell-V1-executes", EphemeralAlertDataKnownIssue },
                { "get-appconsentrequest-powershell-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/612" } },
                { "get-userconsentrequest-powershell-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/612" } },
                { "list-userconsentrequest-powershell-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/612" } },
                { "userconsentrequest-filterbycurrentuser-powershell-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/612" } },
                { "get-callrecord-powershell-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/320" } },
                { "callrecord-getpstncalls-powershell-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/320" } },
                { "get-callrecord-expanded-powershell-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/320" } },
                { "get-callrecord-sessions-powershell-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/320" } },
                { "get-callrecord-sessions-expanded-powershell-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/320" } },
                { "callrecord-getdirectroutingcalls-powershell-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/320" } },
                { "get-connectionoperation-powershell-V1-executes", EphemeralOperationDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/692"} },
                { "get-externalgroup-powershell-V1-executes", MissingPermissionScopeKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/693" } },
                { "get-schema-powershell-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/617" } },
                { "get-externalconnection-powershell-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/617" } },
                { "get-contract-1-powershell-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/322", CustomMessage = "blocked" } },
                { "get-microsoftauthenticatorauthenticationmethod-powershell-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/621" } },
                { "get-attendee-report-powershell-V1-executes", MissingPermissionDescriptionKnownIssue },
                { "get-printconnector-powershell-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/624" } },
                { "get-printershare-capabilities-powershell-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "get-printershare-powershell-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "list-printjob-2-powershell-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "list-group-powershell-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "list-user-powershell-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "get-printoperation-powershell-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "get-printtask-powershell-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/779" } },
                { "get-printusagebyprinter-powershell-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "get-printusagebyuser-powershell-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "get-windowshelloforbusinessauthenticationmethod-powershell-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/638" } },
                { "list-bitlockerrecoverykey-powershell-V1-executes", new KnownIssue(Category.NeedsAnalysis, "Service requires UserAgent") },
                { "list-bitlockerrecoverykey-filter-deviceid-powershell-V1-executes", new KnownIssue(Category.NeedsAnalysis, "Service requires UserAgent") },
                { "contenttype-ispublished-powershell-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/651" } },
                { "get-document-value-powershell-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/502" } },
                { "get-printjob-powershell-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/502" } },
                { "get-printjob-withdocumentdata-powershell-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/502" } },
                { "get-printjob-withtasks-powershell-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/502" } },
                { "get-manager-1-powershell-V1-executes", NoProgrammaticWayKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/511" } },
                { "get-event-based-on-eventmessage-powershell-V1-executes", new KnownIssue(Category.Documentation, "Delegated permissions don't work as documented", "https://github.com/microsoftgraph/microsoft-graph-docs/issues/15507") },
                { "get-onenoteoperation-powershell-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/520" } },
                { "get-workbookoperation-powershell-V1-executes", MissingDataKnownIssue with { GitHubIssue = "https://github.com/microsoftgraph/msgraph-sdk-raptor/issues/524" } },
                { "get-subjectrightsrequest-powershell-V1-executes", MissingPermissionDescriptionKnownIssue },
                { "list-authorednote-powershell-V1-executes", MissingPermissionDescriptionKnownIssue },
                { "subjectrightsrequest-getfinalattachment-powershell-V1-executes", MissingPermissionDescriptionKnownIssue },
                { "subjectrightsrequest-getfinalreport-powershell-V1-executes", MissingPermissionDescriptionKnownIssue },
                { "drive-root-subscriptions-socketio-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "enum-lists-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-all-roomlists-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-all-rooms-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-applicationtemplates-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-calendarpermission-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-call-1-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-call-2-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-comments-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-emailauthenticationmethodconfiguration-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-fido2authenticationmethodconfiguration-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-messagerule-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-messagerules-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-microsoftauthenticatorauthenticationmethodconfiguration-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-onlinemeeting-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-opentypeextension-1-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-opentypeextension-2-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-opentypeextension-4-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-participant-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-participants-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-pivottables-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-printsettings-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-recent-activities-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-replies-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-resources-2-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-rows-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-subscription-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-subscriptions-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-user-presences-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-workbookcomment-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-workbookpivottable-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "item-search-all-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "list-conversation-members-1-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "list-identityapiconnectors-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "list-subjectrightsrequest-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "user-get-calendarview-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "user-reminderview-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-columnsafter-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-columnsbefore-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsabove-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsabove-nocount-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsbelow-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-rowsbelow-nocount-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrange-visibleview-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "workbookrangeview-range-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-deleteditems-count-powershell-V1-executes", MissingPermissionScopeKnownIssue},
                { "get-organizationalbranding-frlocale-bannerlogo-powershell-V1-executes", MissingPermissionScopeKnownIssue},
                { "get-chartpoint-powershell-V1-executes", ExcelItemAtDocumentationKnownIssue },
                { "get-chartpointscollection-powershell-V1-executes", ExcelItemAtDocumentationKnownIssue },
                { "get-chartseries-powershell-V1-executes", ExcelItemAtDocumentationKnownIssue },
                { "get-points-powershell-V1-executes", ExcelItemAtDocumentationKnownIssue },
                { "get-tablerow-powershell-V1-executes", ExcelItemAtDocumentationKnownIssue },
                { "tablerow-range-powershell-V1-executes", ExcelItemAtDocumentationKnownIssue },
                { "get-educationuser-1-powershell-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "channel-getallchannelmessages-1-powershell-V1-executes", ProtectedAPIKnownIssue },
                { "chat-getallmessages-1-powershell-V1-executes", ProtectedAPIKnownIssue },
                { "accessreviewscheduledefinition-filterbycurrentuser-powershell-V1-executes", SDKFunctionParameterKnownIssue },
                { "appconsentrequest-filterbycurrentuser-powershell-V1-executes", SDKFunctionParameterKnownIssue },
                { "user-supportedtimezones-iana-powershell-V1-executes", SDKFunctionParameterKnownIssue },
                { "list-printconnector-2-powershell-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "list-printershare-2-powershell-V1-executes", PermissionsMoreThanOnePermissionKnownIssue },
                { "get-printtasktrigger-powershell-V1-executes", ServiceTaskPrinterKnownIssue },
                { "accesspackageassignment-filterbycurrentuser-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "accesspackageassignmentrequest-filterbycurrentuser-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-columns-from-site-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-transitive-managers-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-to-count-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-hiddenmailfolders-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-group-2-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-singlevaluelegacyextendedproperty-1-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-unifiedroleassignment-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-site-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-permission-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "list-subsites-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-store-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-roleassignments-2-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-post-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-opentypeextension-5-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-opentypeextension-3-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-list-multi-expand-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-list-items-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-message-in-mime-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-list-item-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-single-version-listitem-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-list-2-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-previous-versions-listitem-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-columns-from-list-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "enum-contenttypes-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-list-1-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-groups-withlicenseerrors-count-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-educationuser-2-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-drive-by-site-id-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "site-list-drives-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-datapolicyoperation-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-directory-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-columns-from-contenttype-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-contenttype-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-column-from-contenttype-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-chatmessagechannel-3-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-notebook-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-outlookcategory-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-todotask-1-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "mailfolder-get-hiddenchildfolders-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-group-3-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-linkedresource-1-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-onlinemeeting-user-token-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-sectiongroup-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-term-2-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-todotask-2-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "notebook-get-sections-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-attendancereports-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-linkedresource-2-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-attendancereport-by-id-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-relation-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-resource-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-section-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-set-2-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-term-1-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-todotasklist-2-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "notebook-get-sectiongroups-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "recent-notebooks-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "sectionsgroup-get-sections-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "list-attendancerecord-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "user-delta-select-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "user-delta-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "user-delta-minimal-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "serviceprincipal-delta-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "orgcontact-delta-select-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "orgcontact-delta-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "orgcontact-delta-minimal-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "oauth2permissiongrant-delta-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "notebook-fromweburl-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "message-delta-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "group-delta-with-select-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "group-delta-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "group-delta-minimal-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-shared-root-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-room-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-roomlist-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-presence-multiple-users-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-educationwordresource-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-educationpowerpointresource-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-educationlinkresource-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-educationfileresource-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-educationexcelresource-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-drive-by-id-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-directoryobject-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "get-chatmessagedeltachannel-4-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-chatmessagedeltachannel-3-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-chatmessagedeltachannel-2-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-chatmessagedeltachannel-1-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "educationuser-delta-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "educationschool-delta-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "directoryrole-delta-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "directoryobject-getmemberobjects-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "directoryobject-getmembergroups-me-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "directoryobject-getbyid-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "directoryobject-getavailableextensionproperties-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "contactfolder-delta-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "contact-delta-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "calendar-getschedule-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "application-delta-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "accesspackage-getapplicablepolicyrequirements-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "user-getmailtips-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "directoryobject-getmembergroups-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "educationclass-delta-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-educationmediaresource-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-applicationtemplate-powershell-V1-executes", MissingPermissionScopeKnownIssue },
                { "planner-get-tasks-powershell-V1-executes", NeedsAnalysisKnownIssue },
                { "get-accesspackageassignmentrequest-powershell-V1-executes", NeedsAnalysisKnownIssue },
        };
    }
}
