# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

parameters:
- name: BuildAgentPool
  displayName: Build Agent Pool
  type: string
  default: MsGraphBuildAgentsWindowsRaptor

- name: PipelineTimeout
  displayName: PipelineTimeout
  type: number
  default: 600

trigger: none # disable triggers based on commits.
name: 'Beta PowerShell Snippet Execution Tests'

resources:
 repositories:
   - repository: microsoft-graph-docs
     type: github
     endpoint: georgend
     name: microsoftgraph/microsoft-graph-docs
     ref: main

variables:
  buildConfiguration: 'Release'

jobs:
- job: PowerShellBetaExecutionTests
  pool: ${{ parameters.BuildAgentPool }}
  timeoutInMinutes: ${{ parameters.PipelineTimeout }}
  strategy:
    maxParallel: 1
    matrix:
        PowerShellBetaExecutionTests:
            projectFileName: PowerShellBetaExecutionTests
  steps:
  - template: powershell-execution-tests-template.yml
    parameters:
      projectFileName: $(projectFileName)
      testType: 'Execution'
