# Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.

parameters:
- name: BuildAgentPool
  displayName: Build Agent Pool
  type: string
  default: MsGraphBuildAgentsWindowsRaptor

- name: PipelineTimeout
  displayName: PipelineTimeout
  type: number
  default: 600

- name: PipelineTimeout
  displayName: PipelineTimeout
  type: number
  default: 600

- name: RunName
  displayName: RunName
  type: string
  default: "PowerShell"

- name: Schedule
  displayName: Schedule
  type: string
  default: "0 3 * * WED"  # every Wednesday at 3AM UTC (off hours for Redmond, Nairobi and Montréal)

trigger: none # disable triggers based on commits.
pr: none
name: ${{ parameters.RunName }}

schedules:
  - cron: ${{ parameters.Schedule }}
    displayName: ${{ parameters.RunName }}
    branches:
      include:
      - dev
    always: true

resources:
 repositories:
   - repository: microsoft-graph-docs
     type: github
     endpoint: georgend
     name: microsoftgraph/microsoft-graph-docs
     ref: main

variables:
  buildConfiguration: 'Release'

jobs:
- job: PowerShell
  pool: ${{ parameters.BuildAgentPool }}
  timeoutInMinutes: ${{ parameters.PipelineTimeout }}
  strategy:
    maxParallel: 4
    matrix:
        PowerShellBetaExecutionTests:
            projectFileName: PowerShellBetaExecutionTests
        PowerShellBetaExecutionKnownFailureTests:
            projectFileName: PowerShellBetaExecutionKnownFailureTests
  steps:
  - template: powershell-execution-tests-template.yml
    parameters:
      projectFileName: $(projectFileName)
      testType: 'Execution'
